### ISSUE TITLE
Should Tenant LOB be part of core services?

### ISSUE THREAD

**Issue by amanji** [bcgov/traction#1010]
Should this instead be a demo or example use of Traction?

**Comment by loneil** [comment]
I was recently going to raise whether we needed to keep this around. I don't _think_ any of us are using it.
Personally when I need to test webhook callbacks I just set the tenant up to send to one of the many online webhook receiver sandboxes (obviously not with any production data usage)
To be used with it's current pattern it would also need modification to play with the newer Innkeeper reservation auto-approve patterns. So in it's current state last time I checked it doesn't run properly on a local setup.

**Comment by amanji** [comment]
Agreed. I think it just creates confusion because it's not actually a required service.

**Comment by amanji** [comment]
Resolved by #1074
