### ISSUE TITLE
Should plugins folder have demos?

### ISSUE THREAD

**Issue by amanji** [bcgov/traction#1011]
Wondering if there should be a root level demo folder instead that has different scenarios including plugin and LOB examples.

**Comment by swcurran** [comment]
Wondering the same thing — although I think it makes more sense at the plugin layer. For example, I noticed that the reds-plugin demo from the [BCGov redis-events](https://github.com/bcgov/aries-acapy-plugin-redis-events ) repo didn’t (AFAIK) get moved over to this repo. Should it?

**Comment by loneil** [comment]
What is the plugins demo folder neededfor? It just starts up a subset of Traction stuff and does a reservation. Something easily enough done with starting up normally and going through the Tenant UI.

It _could_ be expanded to do business scenarios with plugins I suppose, but that effort is close to (IMO more valuable) setting up BDD regression tests, which could also be followed to show LOB workflows.

**Comment by swcurran** [comment]
Sorry — didn’t realize this issue was in the traction repo.  I thought the question applied to the aries-acapy-plugins.  Nevermind about my comment.

**Comment by amanji** [comment]
As part of PR #1064, the demo folder has been removed from the `/plugins` directory. A new standalone `/demo` folder exists.

**Comment by amanji** [comment]
Resolved by #1064 and #1074
