### ISSUE TITLE
Tenant UI - Accept Invitation should infer the protocol

### ISSUE THREAD

**Issue by Jsyro** [bcgov/traction#1039]
Given the out-of-band invitations and connection_invitation message urls use different query parameters

Connections [RFC-160](https://github.com/hyperledger/aries-rfcs/tree/main/features/0160-connection-protocol) -> `http://<acapy_url>?c_i=<base64 encode>`
Out-of-Band [RFC-0434](https://github.com/hyperledger/aries-rfcs/blob/main/features/0434-outofband/README.md) -> ` http://<acapy_url>?oob=<base64 encode>`

The UI should check this URL and infer and not require the user to select which protocol the invitation will use. 

AC:

Remove the radio buttons, just drop in the URL and the appropriate acapy endpoint should be used based on the structure of that URL.

**Comment by esune** [comment]
This will be superseeded by #1062 as we drop support for connections (which will be soon deprecated).
