### ISSUE TITLE
Update Tenant UI to use did-exchange

### ISSUE THREAD

**Issue by esune** [bcgov/traction#1062]
Update Tenant UI to use did-exchange to establish new connections, rather the (soon to be deprecated) connections protocol.

*Note:* BC Wallet might not support did-exchange right away, so the update and deprecation of connections needs to be coordinated.

**Comment by loneil** [comment]
Current Tenant UI includes the following calls (of course calling Traction without the UI can do anything in ACA-Py):

 Connections (single and multi), to create invitations
`connections/create-invitation`

![image](https://github.com/bcgov/traction/assets/17445138/0426348d-355c-4e6a-b707-68a0eae9d29b)


OOB (single and multi) to create invitations
`out-of-band/create-invitation`

![image](https://github.com/bcgov/traction/assets/17445138/23bad737-efe0-477d-acbd-4347dcccb221)


Connections and OOB receiving invitations
`connections/receive-invitation`
`out-of-band/receive-invitation`

![image](https://github.com/bcgov/traction/assets/17445138/be7b4eab-bda1-443d-bc91-b167323f07f9)


DID Exchange request
`didexchange/create-request`

![image](https://github.com/bcgov/traction/assets/17445138/2d841354-6509-4762-a58b-3e746bcd6035)

**Comment by Jsyro** [comment]
@krobinsonca The NG Tenure Titles branch uses the connection invitations, which Emiliano notes is soon to be deprecated. 

We should notify them directly and advise them to update/upgrade to using out-of-band messages for connection establishment.
