### ISSUE TITLE
Troubleshooting on demo rpc app startup

### ISSUE THREAD

**Issue by loneil** [bcgov/traction#1107]
Adding notes on some additional troubleshooting docs that can possibly be added from trying out steps here
https://github.com/bcgov/traction/tree/main/demo/plugins/rpc

**Issue with .venv**
On startup of the devcontainer on my machine it didn't seem to be creating venv.
So documented step of `source .venv/bin/activate` was erroring
![image](https://github.com/bcgov/traction/assets/17445138/f771f1f8-9c5c-4850-822a-0476577514dc)

had to create a .venv 
![image](https://github.com/bcgov/traction/assets/17445138/711a13cb-2124-4782-b3ba-1fdc25f7adfb)
then it worked

also to start up debugging had to set a python intepreter in vscode
- command pallette (ctrl shift v) > Select Interpreter
  - Enter interpreter path
  - find
  - select .venv that was created

**Copy Sample env to .env**
- Documentation note to create an .env file
- Check default Traction ports in the sample file

**Comment by amanji** [comment]
Resolved by #1155
