### ISSUE TITLE
Ensure workflows are only executed on the main BCGov repository

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/traction#1146]
Some workflows are not restricted to executing on the main BCGov repository and are therefore attempting to run on forks.

One example is the [delete_images.yaml](https://github.com/bcgov/traction/blob/main/.github/workflows/delete_images.yaml) workflow.  It is running on forks such as this one; https://github.com/swcurran/traction/actions/workflows/delete_images.yaml.

With the most recent run being:
![image](https://github.com/bcgov/traction/assets/10504350/e5cb06b9-7ad8-4c91-8f4a-7b666d9341cb)

**Comment by WadeBarnes** [comment]
@rajpalc7, Please review the all the workflows and ensure they won't run on forks.

**Comment by rajpalc7** [comment]
https://github.com/bcgov/traction/pull/1148/commits - PR for the commit that needs to merged
