### ISSUE TITLE
Delete duplicated endorser service code, use ACA-Py with auto-endorsement

### ISSUE THREAD

**Issue by esune** [bcgov/traction#1251]
The Traction repo has code for an `endorser` that is out of date - https://github.com/bcgov/traction/tree/main/services/endorser.
We should switch to reference and use the code in https://github.com/hyperledger/aries-endorser-service instead.

**Comment by loneil** [comment]
Other alternative could be to just use an endorser _agent_ without the service on top? Is that possible/something that's lighter? Or are the service integrations needed.

On the other hand, having the service running when starting up the whole docker compose is then creating an ecosystem that matches our deployed/production real world Traction cases, so maybe that's better.

**Comment by esune** [comment]
> Other alternative could be to just use an endorser _agent_ without the service on top? Is that possible/something that's lighter? Or are the service integrations needed.

Actually that might be a better idea for Traction in Docker, since we just need to be able to endorse: we can run an ACA-Py agent with auto flags set and that would be good enough and simpler - good point!

**Comment by shanmukh-777** [comment]
Hello,I have a doubt,Do i need to deploy endorser separately in Kubernetes or there is another way of directly giving ledger genesis and endorser did to traction while deploying using helmcharts,so it manages automatically by itself of endorsing transactions sent by tenants using the provided endorser did and ledger genesis.

**Comment by shanmukh-777** [comment]
because in docker there is separate endorser agent but i am unable to find any scripts for endorser agent in helmcharts

**Comment by esune** [comment]
@shanmukh-777 you would have to deploy an endorser agent separately, or connect to an existing one. The endorser service included in the docker-compose file is just there to facilitate local development.

**Comment by shanmukh-777** [comment]
@esune thanks for the confirmation,but is there any charts for aries-endorser-service kubernetes deployment

**Comment by esune** [comment]
> @esune thanks for the confirmation,but is there any charts for aries-endorser-service kubernetes deployment

We do not have native k8s charts for it, but there are OpenShift templates you may be able to take inspiration from [here](https://github.com/bcgov/dts-endorser-service)

**Comment by esune** [comment]
Resolved by #1344
