### ISSUE TITLE
Tenant UI: display read-only ledgers

### ISSUE THREAD

**Issue by esune** [bcgov/traction#1296]
Currently only ledgers for which an endorser exists are displayed in the Tenant UI, but we want to also display a list of ledgers connected in read-only mode that can be used to receive credentials and compose/validate proofs for issuers rooted on those.

**Comment by loneil** [comment]
We list these on the Innkeeper Server Configuration by returning the base wallet config from a special Innkeeper endpoint. Probably could just call the tenant's `config` endpoint and the full ledger list would be in there for a non-innkeeper tenant as well.
