### ISSUE TITLE
(Through Innkeeper UI) Allow permanent delete of a suspended Tenant

### ISSUE THREAD

**Issue by loneil** [bcgov/traction#1317]
UI tweak while we are working on other deletion tasks.

Right now on the Innkeeper UI if you look at deleted Tenants the Delete button isn't there in the table.

![image](https://github.com/user-attachments/assets/da559687-b487-4279-8d15-80bade891592)

For these soft-deleted Tenants the Innkeeper should be able to go in and delete (without having to use Restore to get the delete button back).

Should probably look at passing the status into the modal since suspending an already suspended Tenant wouldn't make sense (only allow permanent delete if already in the suspended state)

![image](https://github.com/user-attachments/assets/cd9698f1-38c1-49a2-b0a6-632a7302b6e5)

Also might be good to adopt the new "Suspended" naming on the other buttons badges that use "Deleted" as the wording. (the "Show/Hide Deleted" button and the "Deleted" badge)

Other minor UI, when deleting the success toast says marked as deleted, should change to permanently deleted, and update the suspended case to use "suspended"

![image](https://github.com/user-attachments/assets/1c260ee3-c96f-4d54-a844-07cc2a428bc2)

**Comment by loneil** [comment]
@Gavinok can probably throw these changes on the pile while working on other deletion tickets?

**Comment by Gavinok** [comment]
Sure thing!
