### ISSUE TITLE
ACA-Py 1.0.1 Upgrade

### ISSUE THREAD

**Issue by esune** [bcgov/traction#1384]
ACA-Py 1.0.1 drops support for AIP 1.0 protocols (connections, issue-credential-1.0, present-proof-1.0). To continue supporting these protocols while adopters migrate to API 2.0 we need to be installing protocols from the `aries-acapy-plugins` repository.

Once this [WIP pull request](https://github.com/hyperledger/aries-acapy-plugins/pull/1056) is merged, we should update our build to ACA-Py 1.0.1 AND add the plugin installation.

**Comment by swcurran** [comment]
1.0.1 deprecates but does not drop the AIP 1.0 protocols. 1.1.x — when we release it will drop those protocols, but 1.0.1 does not.

You may still want to do what is proposed, but it is not required.

**Comment by esune** [comment]
> 1.0.1 deprecates but does not drop the AIP 1.0 protocols. 1.1.x — when we release it will drop those protocols, but 1.0.1 does not.
> 
> You may still want to do what is proposed, but it is not required.

Thanks @swcurran I got mixed-up reading the changelog - it says AIP 1.0 *will* be dropped, not that is *is* dropped 😅.
Will assess what to do then, if we manage to get adopters off AIP 1.0 before it is fully dropped we can avoid this altogether.

**Comment by loneil** [comment]
Updating here https://github.com/bcgov/traction/pull/1398 no major AIP changes or anything needed for consumers as noted above
