### ISSUE TITLE
Remove reference to BPA from readme

### ISSUE THREAD

**Issue by etschelp** [bcgov/traction#178]
Hey guys, would it be possible to remove or rewrite the following sentence in the main readme: "_This project space will be a rewrite of the Business Partner Agent with multitenancy, cloud native architecture and Open APIs._"  The BPA reference causes a lot of confusion and people continuously ask me if the BPA is still being developed, or if it is now Traction, or if Traction is the multi tenancy portion of the BPA.

**Comment by usingtechnology** [comment]
Removing it now @etschelp.
