### ISSUE TITLE
As an Issuer I want to respond to a credential proposal from a Holder

### ISSUE THREAD

**Issue by krobinsonca** [bcgov/traction#391]
AC:

- Issuer is notified of credential proposal
- Issuer can view details of credential proposal
- Issuer can Accept/Decline proposal

See https://github.com/hyperledger/aries-rfcs/blob/main/features/0453-issue-credential-v2/credential-issuance.png

**Comment by krobinsonca** [comment]
AC:

- Issuer is notified of credential proposal
- Issuer can view details of credential proposal
- Issuer can Accept/Decline proposal

See https://github.com/hyperledger/aries-rfcs/blob/main/features/0453-issue-credential-v2/credential-issuance.png

**Comment by hiteshgh** [comment]
@krobinsonca - what is the business use case for this story ,possible a real life example , so that we can AC and point it correctly
