### ISSUE TITLE
View credential in Tenant UI with OCA (for holder)

### ISSUE THREAD

**Issue by krobinsonca** [bcgov/traction#400]
Update the Traction Tenant UI screens to display credentials held by the wallet/agent and display following the OCA spec, using the OCA bundle included with the credential.

**Comment by GurcharanjeetSingh** [comment]
Credentials (formerly My Held Credentials) Adobe XD mock-ups (screen 45 to screen 48) - https://xd.adobe.com/view/20ae96da-b8b6-4dca-8d17-da1c3403613f-75fd/screen/244dd597-2f62-4906-97f4-591352a98385/
