### ISSUE TITLE
Include OCA bundle when issuing a credential

### ISSUE THREAD

**Issue by krobinsonca** [bcgov/traction#401]
As a Traction Tenant Issuer, I want to include an OCA bundle when I issue a credential, so the holder receiving the credential can use the OCA bundle to display/view the contents correctly

- when Tenant defines a new cred def, they can "save" OCA JSON within their own data store (not written to ledger), so that when they offer a credential using the cred def, Traction will include the saved OCA bundle with the offer_credential payload

**Comment by esune** [comment]
Closing as plan for attaching OCA bundles has changed, superseeded by #501.
