### ISSUE TITLE
SPIKE - View presentation in OCA (for verifier)

### ISSUE THREAD

**Issue by krobinsonca** [bcgov/traction#402]
@amanji to bring it up in May 26 OCA meeting as discussion iem

- consider multiple credentials in presentation

- initial UX design is here: https://xd.adobe.com/view/045a1969-719a-4aa5-848f-637ef1b7051a-5109/screen/da6230a7-de4a-486a-9766-85797dd0af1a/

**Comment by amanji** [comment]
Talked with @swcurran and we will set up some time next week (probably after the workshop) to whiteboard some design thoughts on this.
