### ISSUE TITLE
Switch to using BC Gov hosted endorser

### ISSUE THREAD

**Issue by esune** [bcgov/traction#408]
Switch the deployed instances of Traction to use the BC Gov hosted endorser service, rather than having a self-hosted one.

Currently, BC Gov has endorser services deployed for the Candy networks (dev/test/prod). New deployments targeting BCovrin (dev/test/prod) will be required before the switch, unless switching to Candy is an option that should be considered.

**Comment by WadeBarnes** [comment]
Related issue tracking the creation of Sovrin Endorsers; https://github.com/bcgov/DITP-DevOps/issues/28

**Comment by WadeBarnes** [comment]
The endorser services for the BCovrin ledgers have been provisioned.
- dev - [aries-endorser-agent-bcovrin](https://console.apps.silver.devops.gov.bc.ca/k8s/ns/4a9599-dev/deploymentconfigs/aries-endorser-agent-bcovrin)
- test - [aries-endorser-agent-bcovrin](https://console.apps.silver.devops.gov.bc.ca/k8s/ns/4a9599-test/deploymentconfigs/aries-endorser-agent-bcovrin)
- prod (used as a placeholder before transitioning to Sovrin MainNet or CANdy Prod only) - [aries-endorser-agent-bcovrin](https://console.apps.silver.devops.gov.bc.ca/k8s/ns/4a9599-prod/deploymentconfigs/aries-endorser-agent-bcovrin)

**Comment by loneil** [comment]
Any chance I could get access to 4a9599 namespaces?

**Comment by WadeBarnes** [comment]
> Any chance I could get access to 4a9599 namespaces?

Done

**Comment by loneil** [comment]
Thanks Wade!

**Comment by esune** [comment]
This can be closed once https://github.com/bcgov/DITP-DevOps/issues/135 is completed.
