### ISSUE TITLE
As an ACA-Py Tenant Verifier, I want to use a machine-readable governance file to determine if the issuer is in the "trusted list" or not

### ISSUE THREAD

**Issue by krobinsonca** [bcgov/traction#414]
"Machine Readable Governance"

As an ACA-Py Tenant Verifier, I want to use a machine-readable governance file to determine if the issuer is in the "trusted list" or not

AC: 

- Verifier would use a URL to load/cache a list of DIDs of Trusted Issuers of a particular credential (likely pointing to a file in another GH repo)
- After receiving the presentation from the holder, check that the issuer of the presented information is in the list of DIDs

**Comment by esune** [comment]
@krobinsonca I am thinking this issue might need re-assessing before implementing as the conversations around trust registries proceed further and, hopefully, a common pattern is defined for this type of interaction. If you agree, I'd close this issue and reopen a new one once we get deeper into that.

**Comment by krobinsonca** [comment]
Yes, and I think we want a specific use case to target for this.
