### ISSUE TITLE
Traction UI Automated Testing

### ISSUE THREAD

**Issue by krobinsonca** [bcgov/traction#419]
Epic for implementing a unit testing framework

**Comment by jamshale** [comment]
I think there's a substantial framework in place now and this could be closed. Maybe a different ticket for deciding where additional test efforts could be focused but a large majority of the code is testable with the framework in place.

**Comment by loneil** [comment]
Yeah this was for having frontend **unit** test coverage and CICD implementation so it's definitely complete.
Future work could include BDD tests for integration testing against the plugin APIs. Or functional testing (Cypress would be my preference) against the Tenant UI.
