### ISSUE TITLE
SPIKE: Access tenant UI without needed to provide wallet key (OIDC? Credential check?)

### ISSUE THREAD

**Issue by krobinsonca** [bcgov/traction#420]

**Comment by hiteshgh** [comment]
Possible Research effort ( for now )

**Comment by loneil** [comment]
Write up here
https://hackmd.io/@PgFCkYXNR8KNp3kUV-xiPQ/B1f7apTQ2
of problem statement, current state of OIDC usage, and next steps/example solution.

**Comment by loneil** [comment]
@hiteshgh @esune not sure if the writeup/research effort is the AC for this spike ticket, or if it should be reviewed through.
Will need review/discussion for next steps of course but there would be subsequent work/tickets when and if this feature were to get prioritized in at some point.

**Comment by esune** [comment]
I think the writeup is probably enough - I am going through it and adding some thoughts/comments so we keep all the conversation in the same place. We will have to figure out what the priority is for these features anyway before slating them for development, this is a separate conversation so it makes sense to wrap up the research now.

**Comment by esune** [comment]
Closing as per above comment.
