### ISSUE TITLE
Reservation not found - Requester Feedback

### ISSUE THREAD

**Issue by popkinj** [bcgov/traction#428]
Right now the Check Reservation Status handles all errors the same, handle a 404 differently so that the user knows they've entered the wrong res ID.

There are two parts to this ticket. 
1. The backend needs to respond with a "not found" code... which it currently does not.
2. The UI needs to harvest this code and present a "not found" html message. Currently all errors are communicated as Toast notification errors.

AC

1) When a 404 occurs, the error message in the red error toast says "Reservation not found" (or some other text if something else is better)

2) Other non-404 errors just continue to propagate their respective error message forward. If it's not a 404, we don't display "not found".

**Comment by loneil** [comment]
The backend (tenant proxy) **does** return a 404 if a reservation lookiup is not found

Correct ID:
![image](https://user-images.githubusercontent.com/17445138/215193112-3accc2e9-ac68-4bbf-87d2-2c8f193c3051.png)

Incorrect ID
![image](https://user-images.githubusercontent.com/17445138/215193154-e58d1b06-b923-4721-8aa5-9fbe4b68a69f.png)

**Comment by popkinj** [comment]
That's odd. I wonder why it wasn't showing up in the Axios object then.

**Comment by loneil** [comment]
A 404 does come back to the frontend. 
![image](https://user-images.githubusercontent.com/17445138/215199364-b537bf26-f651-4081-9047-ded66b7703d8.png)

**Comment by popkinj** [comment]
Hmmm Yeah.
The responses go straight to the `catch` method and there's no http code. That's why I previously had all errors say `not found`.

**Comment by loneil** [comment]
Yeah it looks like it, so the issue here is to find why it's not reporting a status code back (which axios definitely will do). It might be related to NGinx proxy, or the way the axios instance is set up.

**Comment by loneil** [comment]
Issue here was proxy setting, see notes in https://github.com/bcgov/traction/pull/443

We should just handle error response codes that we don't want to throw as general exceptions with checks for response code in the error handling.
