### ISSUE TITLE
UI Design for "Reservation not Found"

### ISSUE THREAD

**Issue by popkinj** [bcgov/traction#430]
## Fourth and Final Status Indicator for the Reservation Workflow.
When the user requests access to Traction they have to enter personal information to receive a reservation. If they go back to check on the status of their application they have to enter an email and key. If there is no email found in the system we need to show the user that it was not found in the system. That way they can possibly correct spelling and check again.

**Comment by loneil** [comment]
FYI there isn't any lookup for "email not found" nor is there planned to be AFAIK. The key for not found is simply handling the 404 from the reservation ID being wrong.

**Comment by hiteshgh** [comment]
option 1

**Comment by hiteshgh** [comment]
option 1
