### ISSUE TITLE
Tenant API - allow tenants to maintain web hooks

### ISSUE THREAD

**Issue by usingtechnology** [bcgov/traction#433]
Port over `PUT /multitenancy/wallet/{wallet_id}` api to `/tenant`.

Possible to enhance this, but probably best left to the tenant UI if we want separate the fields for easier management.

i.e. allow them to set the image URL and label in discrete UX functions. 

probably shouldn't allow them to set wallet dispatch type?

```
  "image_url": "https://aries.ca/images/sample.png",
  "label": "Alice",
  "wallet_dispatch_type": "default",
  "wallet_webhook_urls": [
    "http://localhost:8022/webhooks"
  ]
```

**Comment by loneil** [comment]
Are multiple webhook URLs fully supported in Aca-Py? If so we could adapt the existing settings page to add multiple. Or simply start with just the one with the existing form.

**Comment by usingtechnology** [comment]
Yes, it’s just an array of strings.
