### ISSUE TITLE
Traction Tenant Token with alternate key/password

### ISSUE THREAD

**Issue by usingtechnology** [bcgov/traction#434]
Currently, we return the tenant gets their `walet_key` and uses that to prove who they are when they get a token. We are using managed wallets, but we should provide a separate key/password that can be used to fetch a token. Tenants (managed) do not need to know their `wallet_key` - this is stored (securely, encrypted) in the db and can be recovered by the admin.

Add new mechanisms to return an alternate key and use that for verification on token fetch/refresh.

A similar concept is in use for reservations...

**Comment by esune** [comment]
Relates to #434

**Comment by loneil** [comment]
#685 is the associated ticket (replaced 420)

**Comment by loneil** [comment]
Completed with
https://github.com/bcgov/traction/issues/685
https://github.com/bcgov/traction/issues/741
https://github.com/bcgov/traction/issues/687
