### ISSUE TITLE
Traction Documentation - Architecture

### ISSUE THREAD

**Issue by usingtechnology** [bcgov/traction#436]
We need some traction architecture diagrams and supporting documentation.
There is nothing since we moved to plugins, the old one as a standalone API has been removed.

**Comment by loneil** [comment]
We've used this one in meetings and demos recently. Can see if more enhancements can be made. Someone on the EMDT Coms team would have the source files

[traction-flow-chart-1600x900-12162022.pdf](https://github.com/bcgov/traction/files/10563897/traction-flow-chart-1600x900-12162022.pdf)

![traction-flow-chart-1600x900-12162022-01](https://user-images.githubusercontent.com/17445138/216207795-c12d6770-5b79-49eb-a34f-f1e096a241af.jpg)

**Comment by usingtechnology** [comment]
thanks @loneil - adding this into PR 435.
