### ISSUE TITLE
As a TenantUI developer, I want to know which acapy/traction plugin calls are needed for HOLDER functionality

### ISSUE THREAD

**Issue by loneil** [bcgov/traction#458]
Before switching tenant UI over to new acapy/plugin calls, this ticket to figure out what we can/can't do just in terms of API calls.

**Comment by usingtechnology** [comment]
starting in on verifying the acapy endpoints, see if we need to enhance or add anything.

**Comment by usingtechnology** [comment]
[issue_and_revoke.txt](https://app.zenhub.com/files/430810764/392957e8-0a27-42a2-b359-b757e5ad40f6/download)
download and rename to issue_and_revoke.py

at the end of the script, this will have a second offer that the holder will reject. the issuer and holder will have `abandoned` items in their lists.  this is the state for "rejected" (it is actually the holder sending a problem report).

I think this covers what we want for basic holder functionality. will / can investigate if we want to add a webhook that listens for `revocation-notification` (holder being notified of revocation). if we can bundle that in the plugin, it may be useful to flag issued credentials...

**Comment by loneil** [comment]
Reviewed script. Tickets to implement are linked to this one (see blocking at top)

**Comment by usingtechnology** [comment]
added PR https://github.com/bcgov/traction/pull/472 that will mark holder credentials as revoked. in the pr is an updated script to illustrate the call to show revoked creds
