### ISSUE TITLE
Investigate: Wallet "Updated By" gets set to now every time a tenant logs in?

### ISSUE THREAD

**Issue by loneil** [bcgov/traction#462]
Not sure if anything needs doing here, but something to look into quick and then action for later.

AC:

- We know if we need to do anything with this?
- A acapy issue is raised if it IS one.
- We have a decision on if to show that field in the Tenant UI if it's not actually the "updated at" time.

Noticed that each time I log in with a tenant then the wallet settings show updated_at as that time

![image.png](https://images.zenhubusercontent.com/5f74f6bfc45ba1b7a96e77cc/35e3aad0-3160-4ab4-b5d5-8af9cf514d55)

So in the tenant settings screen it would not really show you the last time those "settings" have been "updated"

![image.png](https://images.zenhubusercontent.com/5f74f6bfc45ba1b7a96e77cc/82d3fd78-9ecb-4f09-98c9-c3d41f358203)

**Comment by usingtechnology** [comment]
nothing to do here, this is default acapy multitenant stuff. technically, each token would be an update to the wallet. in the basic multitenant, the single `iat` is stored in the wallet record, and in our plugins we followed the same process (store token validity in the wallet).

**Comment by loneil** [comment]
Ok, think  we can't treat the "updated by" as "the settings were last updated" then so I'll adjust it out in the tenant UI
