### ISSUE TITLE
Multi-Ledger Read Support

### ISSUE THREAD

**Issue by esune** [bcgov/traction#476]
As a tenant in Traction, I want to be able to *at least* have read access to multiple ledgers.
A "main" ledger should be marked for write operations - this would match the ledger to which the endorser is conencted to.

As a Tenant Holder, I want to receive credentials issued from both Sovrin and CANdy, so I can participate in multiple ledgers

As a Tenant Verifier, I want to perform a cryptographic check (and check revocation) on the results of a presentation request that contains a content for schemas on both Sovrin and CANdy, so I can verify it is correct

NOTE: As a Tenant Issuer, I want to issue a credentials on only ONE ledger

**Comment by usingtechnology** [comment]
thanks @esune that should get me started. much appreciated.

**Comment by usingtechnology** [comment]
Added [issue 2168](https://github.com/hyperledger/aries-cloudagent-python/issues/2168) and [issue 2167](https://github.com/hyperledger/aries-cloudagent-python/issues/2167). do not multiledger support until resolved.
