### ISSUE TITLE
Spike: Multi-Ledger Write Support

### ISSUE THREAD

**Issue by esune** [bcgov/traction#477]
As a Traction tenant, I want to be able to write to multiple ledgers by submitting the request to the appropriate endorser.

Things to consider:
- is this a "realistic" use-case, or do we expect agents to mostly only target one ledger/network for writes?
- tenant may want to decide which ledgers to request endorsement for (e.g.: only one, all of them. Endorser should be enabled selectively)
- it may be more efficient to just have separate agents on separate Traction instances targeting different ledgers for write purposes

Acceptance Criteria: design document outlining options/implementation steps.

**Comment by WadeBarnes** [comment]
Keep in mind a single tenant would have their resources (Schema(s), Cred-Def(s), etc.) rooted on a single ledger, and the goal would really be to provide the tenants with a choice of which ledger they'd like to be rooted on.

**Comment by esune** [comment]
Closing as done: a tenant will only ever be able to write to one ledger at a time, and the implementation is being handled in #546
