### ISSUE TITLE
Add filter function to tabular data in Traction Tenant UI screens

### ISSUE THREAD

**Issue by krobinsonca** [bcgov/traction#478]
As a Tenant UI user, I want to filter tabular data, so I can find records I'm looking for

See for example: https://primevue.org/datatable

AC:
- All tables' columns have filters for appropriate columns
- Best effort at not having a ton of boilerplate duplication
- Matches Guru's mockups, or if Primevue deviates too much, discuss design compromise with Guru

**Comment by hiteshgh** [comment]
final testing WIP

**Comment by loneil** [comment]
@hiteshgh need a pull request to review before moving code tickets into review

**Comment by Gavinok** [comment]
> @hiteshgh need a pull request to review before moving code tickets into review

Sorry Lucas that was my mistake. I thought since it says review/QA that it would be moved there during testing.
