### ISSUE TITLE
Update Traction Tenant UI for Basic Messaging (chat bubble style)

### ISSUE THREAD

**Issue by krobinsonca** [bcgov/traction#481]
Update the Traction Tenant UI as per this mockup:
https://xd.adobe.com/view/6de87d50-b22b-4f4f-a32c-8cadb2997a25-38bb/

AC:
- On the contact rows there's a button that will nav you to a messages page that it contact-centric for that selected contact (ie https://xd.adobe.com/view/6de87d50-b22b-4f4f-a32c-8cadb2997a25-38bb/screen/2b763930-666d-45cc-90d1-f03b0b1b621d/)
- Ignore the badge for number of unread messages, not supported in Traction
- The message page for the contact shows the view from the UX mockups
- You can send messages
- Receiving would either be a refresh button (or polling), or just have to go back to the page again. Can probably leave that for later. There are no webhook listens for tenants to auto-pop a message reception.
- When you go to "Messages" in the nav bar it has some view of all your messages, either sorted by contact, or just all messages. I don't see any mockups for that so you will need to consult with Guru on what that is supposed to do.
- There's no avatar images or anything so use first name of contact in the avatar badge

**Comment by loneil** [comment]
Note the "is typing" part at the bottom is impossible. So leave that out
![image](https://user-images.githubusercontent.com/17445138/224422811-30571d42-e171-4b52-ae07-fcce3419f280.png)

**Comment by loneil** [comment]
Updated AC

**Comment by esune** [comment]
Closing issue as PR got merged, no more work to do
