### ISSUE TITLE
As a system integrating with ACA-Py, I want to know the migration steps to switch to use Traction, so I can use a central multi-tenanted instance 

### ISSUE THREAD

**Issue by loneil** [bcgov/traction#500]
Description/AC work in progress

This would be the initial knowledge that a operator would need to know in order to stop using a single ACA-Py instance and use a Traction tenant instead.

- "Onboarding" steps, figure out audience
- What modification would they need to take into account for their controller (the part of their system that is currently calling ACA-Py) to call a Traction API instead.
- What API consumer changes are needed (getting a token, not using X-API-KEY, etc)
- What would they need to do to set up a Tenant
- Indy to Askar migration?
- How could the wallet be backed up and moved.

**Comment by esune** [comment]
Duplicate of #708
