### ISSUE TITLE
OCA / OCA Link storage

### ISSUE THREAD

**Issue by usingtechnology** [bcgov/traction#511]
Some R & D for associating Cred Def  with OCA bundle.

Could be as simple as cred def id -> href to oca bundle. 
Just need for a tenant to write it and a wallet (public entity, unauthorized) to read it.

**Comment by esune** [comment]
@usingtechnology this is completed, right? Can the issue be closed?

**Comment by usingtechnology** [comment]
yes 511 can be closed, not sure if there is a frontend to this, but the backend is done.
