### ISSUE TITLE
Error after entering reservation password during onboarding

### ISSUE THREAD

**Issue by krobinsonca** [bcgov/traction#514]
Steps:
1. Create request for new tenant
2. Get approved
3. Check status, enter email and WRONG password

Expected:
1. User is given an error message about wrong password

Actual:
1. User receives Axios error message
-- this happened to multiple users as the password was copied from the email and it seems to have a space after the password

![image.png](https://images.zenhubusercontent.com/63c992039d26589491cde2e7/8d987ca9-06df-4e23-a2a9-29b926f6287e)

**Comment by krobinsonca** [comment]
From sherman:

"sherman — Today at 2:44 PM
it may be advisable to change it from a formatted UUID to just straight text, click and copy. but yeah, new line only thing on it would be good too.
2-for-2 on it definitely means we need to address it quickly"

**Comment by loneil** [comment]
Yeah this is good to note if it's happening. We definitely can remove that extra space. We could also trim whitespace from the password input (though I noted stuff like IDIR or BCeID login does not do that, so a space is wrong in those cases).

I agree that not having a UUID would be ideal as well, so many UUIDs being passed around it might be nice to have the reservation stuff be a different, simpler format.

**Comment by popkinj** [comment]
We could also check if the UUID is a valid UUID. That would give a good clue of a miss-type.

**Comment by popkinj** [comment]
Think I've removed the space after the check-in password. 
There still is the default Axios error when the UUID is wrong. Is part of this ticket to upgrade the axios error to something that makes more sense?

**Comment by krobinsonca** [comment]
@esune - thoughts on the error handling?

**Comment by esune** [comment]
> We could align it with the error on checking status. ![image](https://user-images.githubusercontent.com/479074/227614905-7574a700-f914-4bf3-a6e2-e5de836a5d97.png)

This looks like a god pattern, I'd keep it consistent 👍🏻

**Comment by loneil** [comment]
That's a good style. I would agree with handling 401s from the `check-in` call in that way. (Though remember the password validation is done in the status box below that screenshot above)
It does return a specific error about the password being incorrect in the api call response.

![image](https://user-images.githubusercontent.com/17445138/227645614-0c3590a9-1744-4338-8f2c-a206294fa62f.png)

This should also handle expired passwords so check that 401 message (is it a 401?) as well. You can set the expiry really low with configuration if you docker start up a local Traction

**Comment by popkinj** [comment]
![Screenshot from 2023-03-24 15-11-32](https://user-images.githubusercontent.com/479074/227653544-341dac5b-f5e8-4a2b-bd25-b7d0999645a3.png)

I'm having some weird behavior with my dev env so I'm going to open a PR and do some final testing there.

**Comment by esune** [comment]
Should we surface to the client (in the UI and/or API response) which element in the authentication failed to pass? I thought that wasn't a good pattern from a security perspective, and we should rather say either username or password were incorrect?

**Comment by popkinj** [comment]
> Should we surface to the client (in the UI and/or API response) which element in the authentication failed to pass? I thought that wasn't a good pattern from a security perspective, and we should rather say either username or password were incorrect?

This latest error message is for when the only option is a password. Before this the user has to enter email/reservation ID... There it's mentioned one OR the other is incorrect.

**Comment by popkinj** [comment]
![Screenshot from 2023-03-29 12-50-38](https://user-images.githubusercontent.com/479074/228651774-59b8949c-ae98-4d81-9586-4d6b5b499d7e.png)

**Comment by esune** [comment]
Looks good!
