### ISSUE TITLE
UX Confusion with Wallet ID/Key/Secret terms

### ISSUE THREAD

**Issue by krobinsonca** [bcgov/traction#520]
During an onboarding exercise with BC Gov reps, there was confusion with the terms Wallet ID/Key/Secret - and Registration ID and Password.

We think Key/Secret are the same, but labeled different in different places.

Recommend terms be consistent and clearly described in email content.

Overall the process required quite a bit of "hand-holding"

**Comment by loneil** [comment]
Places I can see the wallet terms/wording

![image](https://user-images.githubusercontent.com/17445138/233443679-1508ebc9-b621-42b3-b5cf-1aa69f87cb5c.png)

![image](https://user-images.githubusercontent.com/17445138/233444889-46f07aba-6f47-4bd2-857e-87a3496de27f.png)

![image](https://user-images.githubusercontent.com/17445138/233445275-3ebad938-e26d-42b8-a3d7-b060ac521062.png)
(spelling mistake to fix there too! "loose")

![image](https://user-images.githubusercontent.com/17445138/233445334-0fb20a4e-cc07-4748-95ba-352684d9d9aa.png)

![image](https://user-images.githubusercontent.com/17445138/233446420-b2abed5b-c098-4536-a0a7-4fd86bff94df.png)



Then there's the "reservation" terms and wording:
![image](https://user-images.githubusercontent.com/17445138/233446113-d3d7fff5-9ab4-4d4c-a240-a67daeb28843.png)

![image](https://user-images.githubusercontent.com/17445138/233446262-13f99b01-33be-4f58-b0de-a0390c7bbd97.png)

![image](https://user-images.githubusercontent.com/17445138/233446622-f9076b19-2571-4571-af08-81870806c3de.png)

**Comment by loneil** [comment]
@esune and/or @krobinsonca 
Thoughts on any needs for this ticket? I think at minimum we'd quickly

- Fix the place it says "wallet secret" instead of key
- Adjust casing (wallet id/wallet key - Wallet ID/Wallet Key) to be consistent?
- Use Reservation ID instead of "reservation number" in that spot? Or maybe "Reservation Number" is better globally for less confusion around "ID"...

Other than that I don't know if there were any thoughts about screen text or email instructions that would alleviate any more confusion? Sherman did change the res ID and PW to not be dashed guids so they at least look a little different now

![image](https://user-images.githubusercontent.com/17445138/233449567-69ce4862-4896-4c04-99b6-9d0bc07a91d5.png)

**Comment by WadeBarnes** [comment]
My two bits ...  Coming more from the technical side perhaps, but I'd momentarily stumble over the term `Wallet Secret` and have to translate that in my head to `Wallet Key`, as the term `Wallet Key` is more prevalent in the industry.  The term `Key` is also more synonymous with unlocking and opening something.

**Comment by esune** [comment]
We might want to chat more about this, and maybe involve UX if necessary. I think we have two different perspectives we need to cater to:
- developers, which will (should!) be more familiar with the industry terms as they will be using them to integrate with the APIs
- business users, which likely will be one step removed from technicalities and will only care about signing-in successfully.

As an added note, for the UI targeting business users we will want to consider that we are looking at potentially adding "other" methods of authentication (OIDC-based, see #420 ) in which case the nomenclature `wallet id/wallet key` will NOT work at all.

**Comment by krobinsonca** [comment]
My two cents on this. I suggest a quick fix for now and then a subsequent review of the whole flow, process of onboarding with the UX folks.

**Comment by esune** [comment]
> 
> For this particular ticket I can at least address the inconsistencies in existing terms/casing I think quickly. Agree with Wade personally that "Key" makes the most sense, can remove the places "secret" is referenced.

Yes, keeping the terminology consistent is all we want to do for *now*. I was just bringing up the fact we should review this as we review authentication methods as you pointed out.
