### ISSUE TITLE
Traction login using wrong Host Header

### ISSUE THREAD

**Issue by wadeking98** [bcgov/traction#531]
## Issue:
When logging in to the traction portal, it sends the login request to the backend with the host header: `Host: traction-tenant-proxy-dev.apps.silver.devops.gov.bc.ca`. As a result, my login fails with the error message: `404
Record not found: wallet_record/<MY_WALLET_ID>`. Here is the full request for reference that I've captured in Burpsuite:
```http
POST /multitenancy/wallet/<MY_WALLET_ID>/token HTTP/1.1
Host: traction-tenant-proxy-dev.apps.silver.devops.gov.bc.ca
Content-Length: 53
Sec-Ch-Ua: "Chromium";v="111", "Not(A:Brand";v="8"
Accept: application/json, text/plain, */*
Content-Type: application/json
Sec-Ch-Ua-Mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.5563.65 Safari/537.36
Sec-Ch-Ua-Platform: "macOS"
Origin: https://tenant-ui-dev.apps.silver.devops.gov.bc.ca
Sec-Fetch-Site: same-site
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://tenant-ui-dev.apps.silver.devops.gov.bc.ca/
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Connection: close

{"wallet_key":"<MY_WALLET_SECRET>"}
```
I've tried logging in across two computers, three operating systems, and three browsers, all with the same result.
**I've confirmed the issue is in the host header** since switching it to `Host: traction-dts-tenant-proxy-dev.apps.silver.devops.gov.bc.ca` allows me to log in (note the `dts` part in this url).
I tested this issue with @esune and he is able to log into my account without a problem. In his case the host header in the login request was set to the `dts` one. So the issue isn't with my account and it's not with my hardware either.

It feels like something weird is going on with some network logic. Maybe a proxy in openshift is assigning the incorrect host header to requests coming form my IP address region??

## Temp Workaround:
Currently I'm bypassing this issue by using burpsuite to replace any occurrences of `Host: traction-tenant-proxy-dev.apps.silver.devops.gov.bc.ca` with `Host: traction-dts-tenant-proxy-dev.apps.silver.devops.gov.bc.ca`

**Comment by loneil** [comment]
What's the URL of the UI you're failing to log in with? I see the "DTS" instance at https://tenant-ui-dts-dev.apps.silver.devops.gov.bc.ca/ talking correctly to the DTS instance of Traction. (I don't have a wallet there to confirm for sure though). 
Maybe configuration was wrong and fixed since this ticket was opened?

If you are trying the NON-dts tenant UI (ie https://tenant-ui-dev.apps.silver.devops.gov.bc.ca/) then the above behaviour would make sense.

**Comment by wadeking98** [comment]
ah, yes thanks, that was the issue. @esune and I must have been using different urls haha, I'm not running into issues anymore.
