### ISSUE TITLE
Per-Tenant settings storage in plugin

### ISSUE THREAD

**Issue by esune** [bcgov/traction#540]
The traction plug-in needs to store settings that are specific to each tenant, such as:
- whether they can connect to the endorser or not (#393)
- whether their did can be public or not (#394)
- other

Touch base with @usingtechnology to review what might already be available.

**Comment by usingtechnology** [comment]
I did not add any of these features to the plugins. Currently, the tenant has no additional storage or API other than the tenant record (tenant_id, tenant name, state, wallet_id). A clean slate for the next developer to add this functionality.

**Comment by esune** [comment]
Thank you for the insight @usingtechnology .

@shaangill025 let's connect before you tackle this so we can come up with a plan together keeping in mind the longer-term view as well.

**Comment by esune** [comment]
@shaangill025 I would suggest creating a document in HackMD as first step documenting what the approach could be so we can refine/review and implement once "stable".

**Comment by shaangill025** [comment]
Design + draft impl HackMD document: https://hackmd.io/@gbeoESqjRxm7oQacVc_3OQ/r1WOaEtQn
