### ISSUE TITLE
Link to Swagger UI in Tenant UI

### ISSUE THREAD

**Issue by esune** [bcgov/traction#544]
As a developer integrating with a Traction tenant, it would be great if I could get to the Swagger UI to inspect the available endpoints and read the documentation from somewhere in the Tenant UI.

**Comment by loneil** [comment]
@esune is the About page an appropriate spot for this? Or any other thoughts about location/UI?

(would go here maybe)
![image](https://user-images.githubusercontent.com/17445138/233435010-0e1195cb-91b5-46d5-87aa-68902cbb40bc.png)

**Comment by esune** [comment]
The about page would work for this purpose I think.

**Comment by loneil** [comment]
👍 
Added to about page under Traction expander. Can see screenshot in attached PR. Used "Swagger UI" as item text, not sure if there's a better wording...

Alternatively could not bury it under Traction expander if we want it more 'findable'

**Comment by esune** [comment]
Resolved by #552
