### ISSUE TITLE
Issues verifying backups when using the backup-container

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/traction#559]
We've started using the [BCDevOps/backup-container](https://github.com/BCDevOps/backup-container) to backup an instance of traction and we're running into errors with the automated backup verification process.

The errors are due to that fact that the traction database and agent instances use the default `postgres` user account for all access to the databases/wallets.  This causes issues for the backup-container which assumes there is a different user account created for "user" level access to the database.  When the backup-container goes to create the local copy of the database for verification using the supplied credentials it errors out because the `postgres` user already exists.  This stops the local postgres instance from starting properly and therefore causes the backup verification process to fail.

While it would be possible to add support for such a use case to the backup-container, it would be better if we could update the traction deployments to use separate accounts for database creation/access and reserve the `postgres` user account for admin use (database creation/administration).  This would align to best practice and conform to what the backup-container is expecting.

**Comment by esune** [comment]
FYI @i5okie

**Comment by esune** [comment]
This should be resolved with the latest version of the charts. We should re-assess after the new deployments have been stood-up - adding blocker issues.

**Comment by esune** [comment]
Closing as new deployments will use a non-privileged user to manage the database schemas after the helm upgrades, and old deployments will all be decommissioned. Can reopen, if required, in the future.
