### ISSUE TITLE
Spike: next steps for CI/CD processes, Helm charts

### ISSUE THREAD

**Issue by esune** [bcgov/traction#562]
This issue is meant to be a spike/planning ticket for the next steps in revamping the CI/CD processes for Traction.

## Background
Traction has over time evolved to the point where it *should* be now possible to use it in a production environment to support multiple clients. The CI/CD processes, however, were established to support the rapid evolution of the product, and the validation of the submitted changes. The Helm charts and the GitHub Action currently work the following way:
- Every time a PR is generated, a new environment/deployment of traction is spun-up for validation
- When a new release is tagged in the repository, environments are updated depending on the name suffix of the tag (`-test`, `-int` or no suffix at all).
- Docker images built for PRs and releases are tagged only with the `sha256` generated from the image signature.
- The Helm charts are currently not regularly maintained and/or reviewed.

## Objectives
To better support the production deployment and maintenance of Traction, for both BCGov and non-BCGov users, the following recommendations are made:
- [x]  Image tags should be NAMED: this means that images built for PRs should be tagged with the PR number, and images built as release artifacts should be tagged with the release version.
- [x] Helm charts should be tied to a release version. Automation *may* be implemented to help maintainers keep-up with these tasks.
- [ ] The Helm chart should be platform-agnostic as much as possible. Native `k8s` objects should be used to describe resources. If platform-specific configurations are required/desirable for BCGov deployments, these should be controlled by a switch in the charts.
- [ ] Automation for PR-based deployments should be maintained, as it support development.
- [ ] Automation for deploying releases should be removed, and transitioned to a separate project specific to the DevOps needs and configurations. The Helm charts in the Traction repository should be used, with custom `values.yaml` files for specific configuration needs.

@WadeBarnes and @i5okie I think the above describes, at a high level, the direction we want to move towards.
Please comment/add feedback as deemed necessary so we can start writing-up tickets specific to each one of the activities identified here.

*Note:* adding this to the `Developer Experience` epic for now as it is the closest Epic fitting the general need, i think.

**Comment by i5okie** [comment]
> * When a new release is tagged in the repository, environments are updated depending on the name suffix of the tag (`-test`, `-int` or no suffix at all).

This is generally accomplished with separate branches for those environments. 
`development`. `test`, `main` for production, and vice versa. Then the pipeline handles the tagging based on the branch. I think going the branch route is a saner approach.

In this case, the logic would be as follows:
- Initial PR to development
- PR development > test/staging
- PR staging > main

Pipelines deploy and tag based on the branch.
test/main branches should be protected from direct pushes and only allow PR merges.

Keeping the environment isolated per branch also is easier to keep track of code changes, history, etc.

**Comment by hiteshgh** [comment]
May be split in 2 stories (13 each)

**Comment by esune** [comment]
I see the charts include a `image.buildtime` parameter which does not make much sense (to me) as it appears more like a build-time inferred attribute, rather than a hard-coded one that needs to be maintained.

@usingtechnology any insight you could provide on this? Is it still something that was used to determine which environment to deploy to?

**Comment by usingtechnology** [comment]
If you've put in true release versioning (not ACA-Py version), then `buildtime` is not useful. It was only useful when we had several deployments in a day/promotions in a week. Just need a way to determine what code has been pushed to which environment.

**Comment by esune** [comment]
I logged issues that I believe cover all the items necessary to complete this spike - see the "blocked issues" section for details. I will be closing this, let me know if you have thoughts @WadeBarnes  and @i5okie .
