### ISSUE TITLE
Innkeeper controls to enable author/issuer functions

### ISSUE THREAD

**Issue by esune** [bcgov/traction#570]
Acceptance Criteria:
- The Innkeeper has controls to explicitly enable a new tenant to connect to an endorser
- The Innkeeper has controls to explicitly enable a new tenant to publish their DID
- Default behaviour should be set using environment variables (e.g.: `ALLOW_PUBLIC_DID_DEFAULT` and `ALLOW_CONNECT_TO_ENDORSER_DEFAULT`)

**Comment by loneil** [comment]
Blocked while waiting for https://github.com/bcgov/traction/pull/604 to be running again with callable API endpoints
