### ISSUE TITLE
Use a Traction instance for the May 31 2023 AnonCreds Workshop

### ISSUE THREAD

**Issue by swcurran** [bcgov/traction#583]
I'm (delighted to be) on the hook to host an AnonCreds workshop with Hyperledger on May 31.  Last I heard we had over 200 people signed up.  I can create the slides and materials easily, but it is called a workshop, and I'm working with Rodolfo Mirando of Roots.ID on that part.  We need a way to have users try out creating a credential, issuing it and verifying it, where more time is spent on the AnonCreds part, and less on the Aries part.

Akiff, Hannah, Aaron and I talked at OSS and think that Traction could be a great way to do this.  We would have each participant requisition and receive a Traction agent. They use that to create a schema or two, connect to a holder and issue a credential (or two) and they do a presentation request with multiple credentials.

To do that we need some effort on the Enterprise Apps team (yes, these will go into issues if we want to go forward):

- deploy (if needed) an instance of Traction that can be used.  Or use an existing one.
- make sure we can support the load -- we'll have as many participants as possible get their instance before the workshop.
- Use BC Wallet as the holder — display QR codes for the interactions.
   - Might also enable having the agent to connect to itself as the holder -- so that participants only need one agent.  Evidently that doesn't work today for some reason.
- Construct a script for them to follow -- with space for them to do their own playing with the schema and the presentation request.

Confirming we can use the BC Wallet — that it is available globally,

More details to follow.

**Comment by esune** [comment]
We should be able to use https://tenant-ui-dts-dev.apps.silver.devops.gov.bc.ca as instance - c.c.: @WadeBarnes 
For the load testing, can we use @usingtechnology script/load tester to figure out the provisioning part? The "genera" usage should be fine, I think, maybe we just tweak and increase the resources a bit.

**Comment by esune** [comment]
@swcurran instance has been deployed ( see https://github.com/bcgov/DITP-DevOps/issues/74 ) and credentials to innkeeper provided separately.

Do you need a hand building/improving the script to follow, or are we good as long as the instance is up and running?
