### ISSUE TITLE
PR deployments are not working

### ISSUE THREAD

**Issue by esune** [bcgov/traction#590]
PR deployments are not working anymore: deployments are failing - see https://github.com/bcgov/traction/pull/586 as example

**Comment by loneil** [comment]
This commit? 
https://github.com/bcgov/traction/commit/b440000d6376580af815af49ca5cc90a7e580c10

Seems to remove the pr# insertion stuff for Tenant UI, but still working for Traction without fullnameOverrride?

**Comment by esune** [comment]
@i5okie see above
