### ISSUE TITLE
SPIKE - OIDC Architecture Decision

### ISSUE THREAD

**Issue by esune** [bcgov/traction#591]
Initial writeup/brainstorming: https://hackmd.io/RE4KjMUPQoScb4MGziKRNg

Acceptance Criteria:
- assess with ACA-Py team direction for managed/unmanaged wallets
- decide on HOW the OIDC mapping will be managed for tenants and users)
- log issues with action items based on decisions

**Comment by esune** [comment]
Relates to #434

**Comment by amanji** [comment]
Are there any materials I can review before our discussion on this?

**Comment by esune** [comment]
> Are there any materials I can review before our discussion on this?

See this writeup by @loneil : https://hackmd.io/RE4KjMUPQoScb4MGziKRNg

**Comment by esune** [comment]
Note from conversation with @amanji and @loneil :
- for OIDC authentication, token/client validation would be required.
- token issuance would be responsibility of another service (i.e.: Keycloak)
- basic auth through api-key would be desirable, especially for services migrating from standalone instances
- tables mapping tenant to OIDC user, OIDC client credentials and api-key would need to be created
- allow tenant users to populate/maintain mappings for their own tenant

Open questions:
- this may not support fully unmanaged wallets, as separate credentials would be stored/required to exchange for the id/key and then token
- where would this be implemented? Options are traction plugin or separate microservice
- are plugins able to access wallet id/key in the aca-py database, or do they need to be stored elsewhere?

Next steps:
Set-up meeting with @usingtechnology to review some of the open questions
