### ISSUE TITLE
Image push action fails when PR is opened from fork

### ISSUE THREAD

**Issue by esune** [bcgov/traction#597]
If a PR is opened from a fork of the `traction` repo, rather than from a branch in the repo itself, the docker image push action fails and consequently the PR environments are not created.

AC:
Review the current behaviour: is this by design and a behaviour we should persist, or should we allow PRs from forks to push images to GHCR and run deployments?

**Comment by WadeBarnes** [comment]
This is by design.  PRs opened from forks do not have access to the repository's secrets for security reasons.

**Comment by esune** [comment]
Closing, for the time being a feature branch in the repository is required to open a PR with full CI/CD automation.
