### ISSUE TITLE
GHCR image and deployment retention strategy

### ISSUE THREAD

**Issue by esune** [bcgov/traction#598]
Images generated by a PR should be cleaned-up from the repository once the PR is closed (merged, abandoned).
PRs should be closed (and deployments destroyed) when left pending for too long (define too long).

**Comment by esune** [comment]
See https://github.com/snok/container-retention-policy

**Comment by esune** [comment]
@rajpalc7 we want to have two different actions:
- one action is to be added to the `on_pr_closed`, and will delete the images created for the PR that is being closed and cleaned-up after.
- another action, to be run periodically (e.g.: once a week) will delete old images that have not been explicitly tagged. This means images that only have the `sha` tag assigned at build time, and no other tag (such as a version, a pr number, etc.)

**Comment by WadeBarnes** [comment]
> See https://github.com/probot/stale for PR/issue management automation.

`probot/stale` is depreciated, https://github.com/actions/stale is the recommended replacement.  I see @rajpalc7 is using the correct one in the PR.
