### ISSUE TITLE
Delay connecting to BC Wallet -- is Traction sending a post-connection trust ping?

### ISSUE THREAD

**Issue by swcurran** [bcgov/traction#609]
We're finding that when a Traction invitation is scanned by the BC Wallet, the connection is established, but the BC Wallet stays on the "Connecting..." page until you manually leave. I checked and determined that the invitation is using RFC 0160 Connections. That protocol lacks a confirmation message (dumb mistake we made years ago...) and so it is convention to always follow the connection protocol completion with a `trust ping` protocols instance.  I suspect that the trust ping may not be happening with Traction, and that's the cause of the delay.

Could someone please investigate this and see if it is a problem and can be addressed?  Would love to have it fixed for the AnonCreds Workshop -- before all the participants start to sign up for their Traction Tenant ahead of the workshop.  They will get a message this Sunday to do that.

Heads up: @esune @loneil -- not sure who wrote that part of Traction and might be the best to take a look.

**Comment by esune** [comment]
The ACA-Py instance Traction is running on is set to auto-ping connections already, so I am skeptical to think the issue is on this end: as far as I know/understand, the connection protocol and endpoints are untouched by the Traction plugin.

The issue *may* be on the multitenancy layer, if anything, but this is a wild guess as well.

**Comment by loneil** [comment]
So the Tenant UI is just calling [/connections/create-invitation](https://traction-tenant-proxy-dev.apps.silver.devops.gov.bc.ca/api/doc#/connection/post_connections_create_invitation)

The resultant invitation_url is what's presented as the QR code.

I think this is just the basic ACA-Py implementation? Not sure if the invitation side on that was plugin-enhanced by Sherman there...
I know we could add a "trust ping" button or something on the UI related to the connection made by the invitation, or some loop that starts pinging while the invitation QR screen is up. But the Tenant UI doesn't know the QR code just got scanned or anything.

Or is this meant to be handled in some callback in the API where the QR code once scanned automates the trust ping? Yeah as mentioned I think auto-ping should be on.

**Comment by swcurran** [comment]
The trust ping would be in the code that processes the response to the connection invitation.  What tells the UI that the connection is established and the QR code modal can be closed?  Or is that left to the user to do?

**Comment by loneil** [comment]
It's just the QR code image up and then you close it manually yeah.
Would be the same as if you copied the image and emailed it to someone, just the QR code it doesn't poll or have any hook back to tell it to do anything.

**Comment by swcurran** [comment]
OK -- let's close it.  The other thing we can check is what triggers the BC Wallet to close the connection screen.  That's the event that is not happening.

**Comment by loneil** [comment]
Could be worth adding a manual trust ping button to the Tenant UI I think just for testing purposes and stuff.

Also interested about this:
> I checked and determined that the invitation is using RFC 0160 Connections. That protocol lacks a confirmation message (dumb mistake we made years ago...) and so it is convention to always follow the connection protocol completion with a trust ping protocols instance. I suspect that the trust ping may not be happening with Traction, and that's the cause of the delay.

If there's a different connection setup we should support through the Tenant UI? The DIDExchange is in there too.

**Comment by loneil** [comment]
FYI @swcurran I tried manually sending the trust ping (I think I got it right) and the wallet still sits at "taking longer than usual"

![image](https://github.com/bcgov/traction/assets/17445138/3e5e5f2a-f2c2-46fe-a472-5ef7e6f5657b)

![Screenshot_20230526-130537](https://github.com/bcgov/traction/assets/17445138/724fe0e3-653c-49fd-a965-3613b79fc0c6)

**Comment by swcurran** [comment]
OK - thanks for testing that.
