### ISSUE TITLE
Add manual trust ping button to invitations

### ISSUE THREAD

**Issue by loneil** [bcgov/traction#610]
As a Tenant UI inviter, I want to send a trust ping to a connection, so that I can test/debug things.
--

From some discussion here https://github.com/bcgov/traction/issues/609

AC:
- On the screen with the QR code for single use invitations there's a button that calls the trust ping endpoint 
- A toast pops with the response
- https://traction-tenant-proxy-dev.apps.silver.devops.gov.bc.ca/api/doc#/trustping/post_connections__conn_id__send_ping
- Same button in the row for a single use invite
- Add the button to the connection screen rows as well
- This just tries trust ping, doesn't do anything with the invitation or connection records based on the result, just for Tenant testing

**Comment by esune** [comment]
I really don't think this is needed: from the UI we could send a message and that should do the same as a trust ping. Trust pings should be handled by the startup parameters and be a fall-back option that the user shouldn't have to deal with manually...

**Comment by swcurran** [comment]
Agreed — it should work without the user doing anything.  I think we can skip this one.  Good to experiment with it though...

**Comment by esune** [comment]
I am unsure on whether to "park it" for future evaluation or close it. It might become useful, possibly, as a developer feature, but not for general Traction UI user consumption, but a developer might be able to send a trust ping manually via API so...

**Comment by swcurran** [comment]
I’d say close it. If we are exposing features like that to end users (and having to explain what it is…), we are in trouble...
