### ISSUE TITLE
Tenant UI developer documentation additions

### ISSUE THREAD

**Issue by loneil** [bcgov/traction#612]
Should catch up on a few Tenant UI developer notes (maybe spawn other tickets if any of these are too big, but as part of this ticket determine direction for all of these at the least)

- In https://github.com/bcgov/traction/tree/develop/services/tenant-ui#internationalization add some details (link to a readme in the appropriate folder?) about using the scripts Akiff developed for filling things in etc.
- Add details about unit tests, coverage, running, etc in https://github.com/bcgov/traction/tree/develop/services/tenant-ui#developing
- Move UX documents to a subfolder in https://github.com/bcgov/traction/tree/develop/services/tenant-ui/docs. Or check with Emiliano if they are appropriate to have in the repository (or should move to other storage)
- Determine if we want to add more videos/need to adjust existing to the https://github.com/bcgov/traction/blob/develop/docs/USE-CASE-ONBOARD.md document. Also if those videos should be hosted elsewhere (YouTube?). Check with Emiliano. If any action on that, create a new ticket.
- Documentation on ngrok usage in Docker scripts for Traction
- Documentation on email mock image that can be used locally and how to use it

**Comment by hiteshgh** [comment]
Gavin Primary
