### ISSUE TITLE
AnonCreds Workshop Questions about Traction

### ISSUE THREAD

**Issue by swcurran** [bcgov/traction#619]
This issue is to collect questions and comments about Traction during the [AnonCreds Workshop on May 31, 2023](https://wiki.hyperledger.org/display/events/Hyperledger+AnonCreds%3A+Using+ZKP+Verifiable+Credentials+Everywhere).

Add a comment to this issue if you are having problems in carrying out the preparations for the Workshop.

**Comment by AnmolSirola** [comment]
When I am connecting my Traction Tenant from my BC Wallet app on mobile, after scaning the resulting QR code with my initialized mobile wallet. I keep getting stuck with this.

![d7713783-3bf0-4688-8277-d4c3b32043c1](https://github.com/bcgov/traction/assets/95535448/b546dd7d-d368-4155-a9d6-d70c31dd7743)

I tired re-installing the app. And restarting my traction tenant. Still I am facing this issue.

**Comment by AnmolSirola** [comment]
@swcurran This is exactly what happened, the status now shows as 'active'. Thank for helping :)

**Comment by flihp27** [comment]
I retried with a multi-use connection and it worked fine

**Comment by alberto-instnt** [comment]
Are you guys using the latest mediator update? Like using askar instead of indy? This seems like an issue regarding the mediator.

**Comment by WadeBarnes** [comment]
> Are you guys using the latest mediator update? Like using askar instead of indy? This seems like an issue regarding the mediator.

The mediator we are using is using the latest version of ACA-Py and askar for secure storage.
