### ISSUE TITLE
Reuse a Presentation Request

### ISSUE THREAD

**Issue by swcurran** [bcgov/traction#620]
As a presentation request developer, it would be nice to be able to create a new presentation request based on an existing one, so I can either send it to another connection, or evolve the Presentation Request JSON.

Suggestion:

- add a button ("Reuse" or an icon) on the line of presentation request in the "Verifications" list.
- on clicking it, open up the usual presentation request dialog, but pre-populated with the data from the previous request (connection, presentation request JSON, auto-verify toggle and optional comment.

The user can update any of the data and click "Submit" as needed.

**Comment by swcurran** [comment]
@esune , @loneil -- is this a trivial one such that it could be done for the Workshop?  If not -- don't push it -- only if it is really easy.  I find myself having to open the Raw Data from a previous send, copy the JSON and then paste it into a new Request. This would eliminate the need to do that.

**Comment by cvarjao** [comment]
If not now maybe later, it would be helpful to use the same proof request template approach as used by the mobile verifier

**Comment by swcurran** [comment]
Indeed, @cvarjao. This issue is even easier, but we should add that as a more extensive feature — having a repository of pre-configured PRs to choose from.

**Comment by loneil** [comment]
@swcurran @esune 
Yeah pretty trivial from a coding standpoint, whipped it up along with the other couple issues in https://github.com/bcgov/traction/pull/622 to try out.
Will leave it up to @esune for product decisions and call whether easy enough to deploy in time to anon creds environment.
