### ISSUE TITLE
Add the "Optional Comment" to the Verifications List screen

### ISSUE THREAD

**Issue by swcurran** [bcgov/traction#621]
It would nice to be able to differentiate presentation requests that have been sent using the "Optional Comment" field, by adding it as a column (perhaps truncated at a reasonable length) to the list.

**Comment by swcurran** [comment]
@esune @loneil -- another one that would be nice to have -- if it is trivial.  It's less important than the #620 suggestion.

**Comment by loneil** [comment]
See comment on https://github.com/bcgov/traction/issues/620#issuecomment-1566510447
