### ISSUE TITLE
Verify a received presentation as verifier who sent the request

### ISSUE THREAD

**Issue by loneil** [bcgov/traction#627]
As a Tenant UI user (verifier), I want an action on a verification record that is in status "presentation_recieved", so that I can trigger the verification of the received presentation.
--

AC:
- On the verifier's list of presentation exchange records, if the status is presentation_recieved have a button that call the appropriate `verify-presentation` endpoint.
- Need a UX/PO call on whether this is just a blind verify button, or if it should pop a window that at least shows the verifier relevant parts of the exchange to review first.

**Comment by esune** [comment]
A first-cut would be to just have a button to perform the verification (assuming auto verification is not enabled). UX might be improved once OCA for presentation requests is formalized better.
