### ISSUE TITLE
Helm Chart Refresh

### ISSUE THREAD

**Issue by esune** [bcgov/traction#633]
Refresh Helm charts based on latest conversations/findings.

Acceptance Criteria:
- [x] Charts should be platform-agnostic
- [ ] ACA-Py should be pulled into its own chart. Keep chart in Traction repo for now, will push to ACA-Py repo as a second step.
- [x] Ensure secret management is consistent: generate on first run, reuse on following runs.
- [x] Add HPA definitions (with enable/disable toggle) for each component.
- [x] Ensure PVC size is configurable in chart settings.
- [x] General clean-up of charts and build processes. As an example, explicitly setting `image.buildtime` on built images and released chartswill not be required anymore.
- [x] For general, default resource allocation take the AnonCreds instance as reference (instance has been sized based on experience with other ACA-Py deployments and load testing).
- [x] Work on #558 as well, as it is related.
- [x] Add chart documentation - Bitnami style - for required settings and optional overrides.
- [x] Environment-specific `values.yaml`  should  be moved in a separate folder in the repo.
- [x] Update GHA to use new chart structure as necessary.

**Notes:** existing deployments will likely be decommissioned/refreshed soon so don't worry excessively about breaking compatibility with existing environments in use.

**Comment by i5okie** [comment]
Draft PR: https://github.com/bcgov/traction/pull/672
