### ISSUE TITLE
Investigate timing issues when connecting to BC Wallet

### ISSUE THREAD

**Issue by esune** [bcgov/traction#634]
When connecting to BC Wallet, it appears that the new connection is `always` very slow to be instantiated or, at the very least, to be detected by the BC Wallet - in Traction/ACA-Py the connection results `active` almost immediately.

Acceptance Criteria:
- Investigate and troubleshoot the behaviour, and log findings/action items as needed.
- Use AnonCreds instance for troubleshooting. Instance can be decommissioned when done.

**Comment by esune** [comment]
Based on input from @amanji and as confirmed by the BC Wallet team, it appears that the BC Wallet will sit, by design, on the spinner screen after a connection until another interaction (credential offer, proof request) is detected.

**Comment by swcurran** [comment]
@cvarjao @knguyenBC @jleach — given the lack of Goal Code in RFC 0160, what about this as a compromise. If we are using RFC 0160, when we get to the timeout (where we currently put the “This is taking longer…” message), we check if the connection is active, and if so, we just happily return to main?  That way, only when it is an Offer/Request and it actually takes a long time do we get undesired (but not bad) behaviour.  The “Connect” use case is a little slower, but not painful — and fixed when we transition to RFC 0023 DID Exchange.

**Comment by esune** [comment]
@swcurran I am inclined to either close this issue and log action items elsewhere (`aries-rfcs`, `aca-py`) or - at least transfer the issue to the `DITP` repo and re-assign it, since it is not Traction-related. Thoughts/objections?

**Comment by swcurran** [comment]
One thought — we could put an instruction in Traction about what to expect if using BC Wallet. Could be helpful for some.
