### ISSUE TITLE
Add mapping tables and API endpoints for authentication mechanisms

### ISSUE THREAD

**Issue by esune** [bcgov/traction#635]
In order to allow authentication to tenants with a method different than wallet id and key, Traction will need to keep track of mappings to determine which user is supposed to have access to which tenant.

Acceptance Criteria:
- [ ] Implement appropriate data structure(s) to store mappings for userid/tenant, client-id/tenant, api-key/tenant
- [ ] Add endpoints (with Swagger docs) to maintain these lists
- [ ] Innkeeper should be able to see/manage mappings for any tenant (first user set-up and assistance)
- [ ] Tenant should only be able to manage mappings for its own users/clients/api-keys

Note: this *could* be part of the `multitenant_provider` plugin, or its own plugin. Evaluate pros/cons and discuss with the team where best to put this functionality. If the decision is to create separate plugin, it might be best to create a new repo.

**Comment by loneil** [comment]
Closing, replaced by #685 and #686
