### ISSUE TITLE
SPIKE - Customizable Theming

### ISSUE THREAD

**Issue by esune** [bcgov/traction#647]
Review what possibilities we have to implement customizable theming. This may include, but not be limited to:
- primary/secondary colors
- fonts
- logos/images

**Comment by loneil** [comment]
@Gavinok set up a chat when you get to starting on this one, I can go over how the styling of the app works and direction we'd want to ideally head.
PrimeVue has theming more available now so this is where we would want to start looking
https://primevue.org/theming

**Comment by Gavinok** [comment]
Path forward is to complete #674 for now and once PrimeVue 4.0 is released work on #675 to make this future proof
