### ISSUE TITLE
Refresh on User -> Profile screen takes user to login -- add a refresh button

### ISSUE THREAD

**Issue by swcurran** [bcgov/traction#651]
When the connection to the endorser is not immediately activated, there is a message: `Connection not Active yet, refresh or come back later.  State: request`.  There is no refresh icon, and hitting reload (Mac Cmd-R) logs the user out and to the login screen.

At least add a Refresh icon to the page.  Nice to have would be the ability to do a reload without being logged out of Traction.

---

AC
1) Add a Refresh icon/button to the user profile and user settings page

Note : These kind of issues may be eliminated once we review the overall 'store' strategy

**Comment by cvarjao** [comment]
refreshing at any page takes back to the login page

**Comment by esune** [comment]
I am leaning towards closing this issue and completing https://github.com/bcgov/traction/issues/655 instead as it would solve this problem without adding a "hack" in the page.

**Comment by swcurran** [comment]
Agree that #655 would be good. Would that enable “behind the scenes” refreshes/auto-detection of updates, or would manual refreshes still be needed? If manual ones are needed, might as well add the button, since it is on all the other pages.

**Comment by hiteshgh** [comment]
link to #655

**Comment by loneil** [comment]
This gets covered by some refresh generalization I've handled in https://github.com/bcgov/traction/pull/677

So you can refresh the profile component same as other ones.

Does not handle #655 for browser refresh/caching, which is still valuable to do at some point
