### ISSUE TITLE
Add an credential definition based on any existing/published schema from any ledger

### ISSUE THREAD

**Issue by cvarjao** [bcgov/traction#658]

**Comment by esune** [comment]
This is dependent on multi-ledger compatibility, which is currently a work in progress - as-is Traction only supports one ledger.

**Comment by swcurran** [comment]
If I am understanding this request, this is not supported in Indy.

A CredDef must be on the same Indy ledger as the schema on which it is based.  If you want issuers on different ledgers to use the "same" schema, you have to duplicate the schema on each ledger.

Closing -- please reopen if you mean something else.
