### ISSUE TITLE
Sometimes created/imported schema does NOT show up at all in the list

### ISSUE THREAD

**Issue by cvarjao** [bcgov/traction#659]
Environment: https://tenant-ui-dev.apps.silver.devops.gov.bc.ca/
Tenant ID: e036a51d-a0b3-4f4a-9e05-c4e9e6f61acc

**Comment by loneil** [comment]
Do you have an example/environment? I've never seen a schema fail to make it to the plugin storage. It can be slow occasionally and not appear until refreshing the table.

**Comment by jamshale** [comment]
I thought I saw this locally when ngrok timed-out and the schema creation failed. Possibly the toast notification isn't working correctly. If someone takes this it's something to consider.

**Comment by esune** [comment]
@jamshale I believe you completed this as part of the Tenant UI refresh you did recently, can you confirm? If that is the case we can close.

**Comment by jamshale** [comment]
@esune Yes, I believe this was the same confusion I had. I improved the UI and it should be more clear. If you try to import a schema that already exists you'll still get this behaviour but there will be a success message now.

Closing.
