### ISSUE TITLE
Select which Ledger/Endorser to connect to - Tenant UI

### ISSUE THREAD

**Issue by esune** [bcgov/traction#681]
As a tenant, I should be able to pick which ledger my agent should have write privileges on - when running in a multi-ledger instance.

Logic flow:
- New tenant request
- Innkeeper authorizes tenant to become issuer
- Tenant selects ledger/endorser to be rooted on from list of available options
- Once rooted, no change is allowed

Acceptance Criteria:
- [ ] Invoke innkeeper APIs to select ledger/endorser
- [ ] Update UI/UX to provide tenant with appropriate selection controls - innkeeper would just authorize the tenant to become an issuer, the tenant selects which ledger to be rooted on

**Comment by loneil** [comment]
Need to possibly consider all of the decisions coming out of https://github.com/bcgov/DITP/issues/31 for what the interface of this ticket would be.

cc @esune

**Comment by loneil** [comment]
Does completion of https://github.com/bcgov/traction/issues/546 mean the ACA-Py and/or plugin API calls support what's needed for this?

For grooming/planning @esune / @shaangill025 did you want me to take Tenant UI frontend part of this for next sprint then?

**Comment by esune** [comment]
@loneil correct, #546 exposes the APIs required for this to work. @shaangill025 please coordinate with @loneil for the UI/UX design and development.

**Comment by hiteshgh** [comment]
@shaangill025  to log bug
