### ISSUE TITLE
Remove curl image dependency in agent deployment descriptor

### ISSUE THREAD

**Issue by esune** [bcgov/traction#690]
When deploying the agent, there is a `curl` command that is executed in a container within the agent pod (see `charts/traction/templates/acapy/deployment.yaml`) that registers the agent's DID on the ledger. This is not supported by all ledgers and should be handled in a more generic way.

In particular, this should not be required for the main wallet, when running an agent in multi-tenancy mode: the main wallet should run in read-only mode as it does not have any interaction with the ledger, it is just acting as a "coordinator" for the tenants.

**Comment by i5okie** [comment]
Just adding this from a duplicate issue I just closed. This is the code:
The registration [init-container](https://github.com/bcgov/traction/blob/main/charts/traction/templates/acapy/deployment.yaml#L32-L47), and related [helper code](https://github.com/bcgov/traction/blob/main/charts/traction/templates/_helpers.tpl#L211-L218) should be removed from the helm chart.

**Comment by i5okie** [comment]
made a comment in the PR, need to fix the multi-tenancy ledger functionality
