### ISSUE TITLE
Regression test new bc0192 environments

### ISSUE THREAD

**Issue by loneil** [bcgov/traction#710]
Ticket to track testing out of interoperability and functionality of new Traction deployments

Use Tenant UI for all the following, that will confirm environmental setup for core Traction plugin functionality and desired ACA-Py settings. Intent is not to verify all ACA-Py behaviour (that's what Aries Test Harness is for).

- [x] bc0192-dev
**Tenant Creation**
  - [x] Can log in as Innkeeper with key
  - [x] Can log in as Innkeeper with IDIR
  - [x] Create reservation
  - [x] Innkeeper and Tenant received emails, email links return to appropriate URL
  - [x] Approve reservation as Innkeeper, password sent to tenant
  - [x] Tenant created once entering password on approved reservation status, tenant appears in Innkeeper list
  - [x] Log in with Tenant wallet id/key
  - [x] Innkeeper approves to be an issuer, tenant can connect to endorser, register DID
  - [x] Add a webhook endpoint in tenant settings and confirm for steps below that webhooks send
**Connections/messaging**
  - [x] Create single use and multi-use invitations
  - [x] Accept invitation from another Traction tenant
  - [x] Accept invitation in a BC Wallet (scan QR)
  - [x] Messaging to connections
**Schema/cred creation/Issuance**
  - [x] Create a schema, create a cred from the schema
  - [x] Repeat for revocable cred
  - [x] Offer creds to Traction and BC Wallet connections, accept them
  - [x] Revoke cred
**Verify**
  - [x] Send a proof request to another tenant
  - [x] Send a PR from the BC Wallet to the Traction tenant

- [ ] bc0192-test
**Tenant Creation**
  - [ ] Can log in as Innkeeper with key
  - [ ] Can log in as Innkeeper with IDIR
  - [ ] Create reservation
  - [ ] Innkeeper and Tenant received emails, email links return to appropriate URL
  - [ ] Approve reservation as Innkeeper, password sent to tenant
  - [ ] Tenant created once entering password on approved reservation status, tenant appears in Innkeeper list
  - [ ] Log in with Tenant wallet id/key
  - [ ] Innkeeper approves to be an issuer, tenant can connect to endorser, register DID
  - [ ] Add a webhook endpoint in tenant settings and confirm for steps below that webhooks send
**Connections/messaging**
  - [ ] Create single use and multi-use invitations
  - [ ] Accept invitation from another Traction tenant
  - [ ] Accept invitation in a BC Wallet (scan QR)
  - [ ] Messaging to connections
**Schema/cred creation/Issuance**
  - [ ] Create a schema, create a cred from the schema
  - [ ] Repeat for revocable cred
  - [ ] Offer creds to Traction and BC Wallet connections, accept them
  - [ ] Revoke cred
**Verify**
  - [ ] Send a proof request to another tenant
  - [ ] Send a PR from the BC Wallet to the Traction tenant

- [ ] bc0192-prod
**Tenant Creation**
  - [ ] Can log in as Innkeeper with key
  - [ ] Can log in as Innkeeper with IDIR
  - [ ] Create reservation
  - [ ] Innkeeper and Tenant received emails, email links return to appropriate URL
  - [ ] Approve reservation as Innkeeper, password sent to tenant
  - [ ] Tenant created once entering password on approved reservation status, tenant appears in Innkeeper list
  - [ ] Log in with Tenant wallet id/key
  - [ ] Innkeeper approves to be an issuer, tenant can connect to endorser, register DID
  - [ ] Add a webhook endpoint in tenant settings and confirm for steps below that webhooks send
**Connections/messaging**
  - [ ] Create single use and multi-use invitations
  - [ ] Accept invitation from another Traction tenant
  - [ ] Accept invitation in a BC Wallet (scan QR)
  - [ ] Messaging to connections
**Schema/cred creation/Issuance**
  - [ ] Create a schema, create a cred from the schema
  - [ ] Repeat for revocable cred
  - [ ] Offer creds to Traction and BC Wallet connections, accept them
  - [ ] Revoke cred
**Verify**
  - [ ] Send a proof request to another tenant
  - [ ] Send a PR from the BC Wallet to the Traction tenant

**Comment by loneil** [comment]
Only DEV is deployed with up to date version of Traction at this time, so siloing this ticket to confirming the dev deployment with 0.8.3pre and all the new helm stuff.

**Comment by swcurran** [comment]
FYI — the 0.9.0-rc0 ACA-Py is available. We’d like it to get used, so if you can easily replace the 0.8.3pre with 0.9.0-rc0, that would be appreciated.  Wade is doing some smoke testing of the release, but the more experience the better before we publish the final version.

**Comment by loneil** [comment]
@swcurran yeah absolutely, I assume it's this image tag here
https://github.com/hyperledger/aries-cloudagent-python/pkgs/container/aries-cloudagent-python/111618235?tag=py3.9-0.9.0-rc0
?

If so I can add that in to Traction shortly to try out.

**Comment by swcurran** [comment]
Yes — that’s the one.
