### ISSUE TITLE
Feature-flags for non-production features

### ISSUE THREAD

**Issue by esune** [bcgov/traction#717]
We need to add feature flags to turn on/off functionality in the Tenant UI that may NOT be required in production, but is beneficial in lower environments and sandbox deployments.

Functionality that needs a switch to turn  it off:
- [ ] Creating Schema
- [ ] Creating Credential Definition
- [ ] Issuing/revoking credentials
- [ ] Sending messages to a connection

Functionality that should stay ON always:
- [ ] Tenant settings customization
- [ ] Create/Receive connection invitation (useful for OOB-initiated connections)
- [ ] List existing connections
- [ ] List held credentials

T.B.D.:
- [ ] OCA Bundle association wizard? (this would only affect Traction)

@loneil please feel free to chime in if you have further ideas, or if I forgot a feature that should be disabled or always on (and currently exists).

Acceptance Criteria:
- [ ] A feature flag environment variable is added, and turning it on/off will enable/disable (or even hide) the relevant parts in the Tenant UI
- [ ] The feature flag environment variable is added to the Tenant UI Helm chart

**Comment by popkinj** [comment]
Thanks for these @esune 
For any of the above that may have backend (node) interfaces... Do you want the flag to also block those as well. As opposed to just hiding the user interface.

**Comment by loneil** [comment]
@popkinj There's no Node involved in these features
