### ISSUE TITLE
SPIKE: Assess required changes for non-automatic endorsement

### ISSUE THREAD

**Issue by esune** [bcgov/traction#726]
Currently, Traction expects an Endorser to automatically (and almost instantaneously) accept connections and endorsement requests coming from a tenant. In reality, this will not be the behaviour that is encountered with production networks.

**Acceptance Criteria:** assess and document current behaviour and required changes when using endorsers that will not automatically respond to requests. Changes may be localized to the Tenant UI, more likely some changes will be needed in the Traction plugin as well. 

Interactions to pay attention to:
- non-automatic connection requests from a tenant to an endorser
- non-automatic DID publishing
- non-automatic schema/creddef creation
- ~~endorser agent not writing the transaction after endorsement was provided, but tenant having to do so (see endorsement options [here](https://github.com/hyperledger/aries-cloudagent-python/blob/main/Endorser.md#configuring-aca-py-for-auto-or-manual-endorsement))~~

**Comment by WadeBarnes** [comment]
The `Government of British Columbia - Endorser` services will not write any transactions to the ledger apart from, perhaps, the DID for a newly approved author - some investigation still needed here.  The intent is to keep the endorser services as purely endorser services that endorser a transaction for an author and hand the signed transaction back to the author to write to the ledger.

**Comment by swcurran** [comment]
I don’t think we should be so hard and fast on that. I don’t think it matters who writes the transaction, as long as it gets written.  I’m thinking down the line where the endorser is writing to ~~ledgers~~ verifiable data registries other than Indy. We still want the same functionality — approval before writing — but the target of the writing might be different. It might be easier to have the endorser do the writing.

Happy to discuss this further.

**Comment by esune** [comment]
This has possibly been duplicated by #797
