### ISSUE TITLE
[Helm Chart] Secret key with empty string gets removed on upgrade

### ISSUE THREAD

**Issue by i5okie** [bcgov/traction#728]
Issue discovered in testing of https://github.com/bcgov/traction/pull/725

- If a secret exists and the value is empty, the helm upgrade command still succeeds, but the empty key is removed.
   - Re-running helm upgrade with .generated set to true succeeds but the key is not re-created.
   - Re-running helm upgrade with .generated set to false succeeds but the key is re-created with the value read from Values.

**Comment by esune** [comment]
@i5okie is this still an issue?

**Comment by i5okie** [comment]
This has not been addressed yet. This was left on the back burner to see if it comes up again as running into this issue may be a pretty rare edge case scenario.
