### ISSUE TITLE
PrimeVue library update causes issues with certain unit tests

### ISSUE THREAD

**Issue by loneil** [bcgov/traction#753]
Tried updating PrimeVue to `3.32.0` and all the behaviour and look and feel in the running app appears to be working as expected.

Unit tests failed though. (some were expected snapshot changes that updating fixes).

All of them (9 tests) failing as shown below on the 
`expect(wrapper.getComponent({ name: 'Dialog' }).vm.visible).toBe(true);` type of checks

![image](https://github.com/bcgov/traction/assets/17445138/f8759cea-3816-433c-b0ee-21f4e2a1d3fd)

Dialogs are indeed working fine in the running app.

Didn't have a chance to play around to try and fix much and can't figure out immediately, so backloging primvue update with this ticket.

**Comment by loneil** [comment]
@jamshale any idea off the top of your head on what's causing this?

**Comment by jamshale** [comment]
I'll have a look. Maybe the component isn't called `Dialog` anymore.

**Comment by loneil** [comment]
Thanks! If it's a simple fix can just let me know and I'll include it then with other lib updates in https://github.com/bcgov/traction/pull/752

**Comment by jamshale** [comment]
Hmmm. The entire componentVM properties are missing in version 3.32.0 making all the tests that use getComponent().vm fail. 

It still exists in 3.31.0 and all the tests pass. No idea why they did that or if it was on purpose.

I'll try figure out what to do about it. They might get more complaints about this version.

Maybe just upgrade to 3.31.0 for now? They only released 0.32.0 today.

**Comment by jamshale** [comment]
Actually I messed up. This broke actually broke with 3.30 :/

Still looking into it.

**Comment by jamshale** [comment]
Ugh. Not sure why this changed but the fix is using attributes instead of the vm object. It returns a string though.

`expect(wrapper.getComponent({ name: 'Dialog' }).vm.visible).toBe(true);`
would change to:
`expect(wrapper.getComponent({ name: 'Dialog' }).attributes().visible).toBe('true');`

I can do this upgrade if you want.

**Comment by loneil** [comment]
Haha nice, they love to change things in PrimeVue like that...

I can add this to my PR for other updates, then I can test it all together as one. I'll just add those test changes and try them out. 
Thanks for figuring it out! 😄

**Comment by jamshale** [comment]
I was able to get the upgrade working by doing these changes and updating a few snapshots.
I had to delete the App.test.ts as well. It started failing for some reason but was a useless test anyway.

Let me know if you have any issues and I can do a PR for the primevue upgrade separately.

**Comment by loneil** [comment]
Thanks, yeah I was just looking at that App.test one locally as well but will remove for now too.

I'll link this issue to the PR I have and included these updates, will regression test all the library updates together there quickly.
