### ISSUE TITLE
Display tenant's public DID value before it is written to the ledger

### ISSUE THREAD

**Issue by esune** [bcgov/traction#757]
In some scenarios, the value for the "candidate" public DID for a tenant needs to be displayed to the user *BEFORE* the transaction to publish it is successfully endorsed.

Acceptance Criteria:
Update the UI to display the public DID (or did to be public) even if the request to have it endorsed is rejected or it doesn't receive immediate response from the endorser (i.e.: it is pending).

**Comment by swcurran** [comment]
Suggest that the UI indicate both the public DID and it’s current status — at least published, pending publication, and perhaps, publish failed. Pending publication should not be considered a failure.

**Comment by loneil** [comment]
See series of calls in `getPublicDid` in `tenantStore.ts`. 
Those can be split into individual steps instead of the single step.

**Comment by esune** [comment]
> Suggest that the UI indicate both the public DID and it’s current status — at least published, pending publication, and perhaps, publish failed. Pending publication should not be considered a failure.

I agree with @swcurran. We could keep the single toggle as control, and surface/display the information based on how far the process gets:
- the did can be created and displayed right away, flagging it as private or not (yet) public
- if the transaction endorsement is completed, it would be marked/highlighted as public
- if the transaction is pending (how do we know we have a DID publishing transaction pending endorsement) we can display the pending status
- if the transaction is rejected, a failure state is displayed and the did is displayed as not (yet) public

**Comment by loneil** [comment]
Just might need additional controls on the FE to retry each step for when one does not complete?

**Comment by loneil** [comment]
Depended on UX/UI direction from #681

**Comment by loneil** [comment]
Details on Endorser steps and Traction 'make-issuer' flow here https://github.com/bcgov/traction/issues/797

This ticket will need to change the multi-ledger connect/switch UX introduced in #681 to accommodate above.
