### ISSUE TITLE
Make Tenant UI  a default component in Traction chart

### ISSUE THREAD

**Issue by esune** [bcgov/traction#761]
Currently, Traction and the Tenant UI are two separate, independent charts. If the Traction charts is not already deployed, and the Tenant UI values are not updated accordingly, deployments will fail (or run and not work, which is even harder to troubleshoot).

It would make more sense to have the Tenant UI as a component of the Traction chart that can be deployed (or not) using a flag in the values file, rather than having this implicit hard dependency.

**Comment by hiteshgh** [comment]
Needs Huddle
