### ISSUE TITLE
You can get a token without supplying the wallet key

### ISSUE THREAD

**Issue by loneil** [bcgov/traction#771]
As a Traction operator, I don't want people taking advantage of the ACA-Py multi-tenancy endpoint giving tokens out without the wallet key, so that there is security.
--

We've handled this in the Traction Tenant token endpoint (from innkeeper plugin) but should handle in our override of the Wallet Token endpoint from the muiltitenant provider plugin. Block request if no wallet ID is provided (ACA-Py at least fails it on mismatched wallet key). This will safeguard Traction at least from this security issue.

AC:
- A blank string wallet ID, or no wallet ID called to multitenancy/wallet/{wallet_id}/token returns an unauthorized response
- Underlying issue discussed with ACA-Py team and ticket created (if not already documented)

![image](https://github.com/bcgov/traction/assets/17445138/7dc031bd-d2eb-44fd-aa09-a3a09fc092c4)

**Comment by loneil** [comment]
Some existing context

https://github.com/hyperledger/aries-cloudagent-python/issues/1681

https://github.com/hyperledger/aries-cloudagent-python/issues/1611

@esune can add any more details if needed after conversations here.

**Comment by esune** [comment]
Thank you @loneil. As per our conversation from yesterday, having the Traction plug-in fix this as part of the (already occurring) override for the endpoint handler seems like a good direction, at least for now and for our specific use-case.
We can then reassess if/when the endpoint changes in ACA-Py - the current behaviour does not seem correct, but based on the linked issues there may be considerations related to unmanaged wallets that would require extra thinking before we can push a change there.
