### ISSUE TITLE
Configuration for customizable form fields

### ISSUE THREAD

**Issue by loneil** [bcgov/traction#774]
Need a mechanism for a Traction operator to specify and alter as needed their reservation form schema.

Not sure exact best implementation, but in meeting we discussed a file could be best.

AC
- Configuration can be changed such that when redeploying or restarting the app, the reservation form will change to adapt to the altered form schema
- None of this is dependent on **building** the Tenant UI, it's all runtime config
- No hard coded values needed (other than required email, tenant name)
- Helm charts work for specifying this per environment
- Local Docker startup can use a configurable form
- There is a default form field setup in the codebase

**Comment by loneil** [comment]
From discussion with @i5okie / @esune / @popkinj

**Comment by esune** [comment]
@popkinj I don't think the helm charts were updated to include the configuration file for the dynamic fields (i.e.: the non-standard ones). We might want to tackle this next to wrap-up the work.

**Comment by popkinj** [comment]
Sure thing @esune . It can be my top priority tomorrow morning.

**Comment by esune** [comment]
I see a PR was merged and one is closed: is this ticket done? If so, please close it.
