### ISSUE TITLE
Innkeeper UI changes for configurable reservation forms

### ISSUE THREAD

**Issue by loneil** [bcgov/traction#775]
As an Innkeeper Tenant UI user, I want to see the details of a reservation record even if it's a dynamic form, so that I can inspect reservations before actioning them.
--

Right now the relational fields in a reservation work fine in the Innkeeper reservations and history tables.
Example:
![image](https://github.com/bcgov/traction/assets/17445138/194cb508-beff-41a4-b229-7dadf88457d7)

If the fields are dynamic and customizable need to know how to handle that in the table

AC:
-TBD

**Comment by hiteshgh** [comment]
minimal scope/AC

**Comment by loneil** [comment]
Easiest thing here
- Remove the reservation form columns that are not the 2 mandatory ones. SO just leave Tenant Name and Email
- Add the typical Row expander UI to display the whole Reservation, where the custom form fields would be

I would do at least the above before merging in the Reservation form ticket, should be quick to do this as a MVP.

In the future (or if a priority now, but do above first), could have the form definition config contain some metadata about "Show in Innkeeper Table" or something, and then dynamically add the columns the system wants shown at a glance.

cc @esune @popkinj

**Comment by esune** [comment]
Resolved by #645
