### ISSUE TITLE
Configurable Reservation Form support i18n

### ISSUE THREAD

**Issue by loneil** [bcgov/traction#779]
As a Traction operator, I want my defined custom reservation form to support internationalization, so that it can use multiple languages
--

Not sure how this would be done...
Note also at this time the login/reservation page doesn't actually have a translation switcher, but should at some point in the future (that part unrelated to this ticket)

AC
- You can have translations for the reservation form, defined by the form maker

**Comment by popkinj** [comment]
In the perfect world [this would](https://github.com/mokkabonna/vue-vuelidate-jsonschema) be able to drop into our existing setup. Should start here then possibly follow this [recipe](https://www.vuemastery.com/blog/Validating-Schema-Driven-forms-with-Vuelidate/) otherwise.
