### ISSUE TITLE
Tails directory is not being persisted

### ISSUE THREAD

**Issue by esune** [bcgov/traction#786]
Traction needs a persisted directory at `/home/aries/.indy_client/tails` for the tails files to be persisted and shared across ACA-Py pods. This needs to be added to the Traction chart, see https://github.com/bcgov/trust-over-ip-configurations/blob/main/openshift/templates/issuer-agent/issuer-agent-deploy.yaml and look for `TAILS_FILES_DIR` for an example.

**Comment by swcurran** [comment]
This is probably a minor issue and easily done. But as of the latest CL Signature, as long as the creator of the Tails File can publish it to the Tails Server, it does not need to be kept locally.  Of course, I’m not sure what would happen if the publish to the Tails Server failed...

**Comment by esune** [comment]
> This is probably a minor issue and easily done. But as of the latest CL Signature, as long as the creator of the Tails File can publish it to the Tails Server, it does not need to be kept locally. Of course, I’m not sure what would happen if the publish to the Tails Server failed...

The issue is with the current instances of ACA-Py requiring the tails file to be locally stored: not having a persisted volume attached to *ALL* pods would cause the file to be lost if the pod that generated it was destroyed, and the other pods would not have access to it.

It is an easy fix that allows us to not have to worry about enabling autoscaling immediately, and is already implemented in other deployments.

**Comment by loneil** [comment]
As well if the call the results in creating this file lands on pod number 1, and then a subsequent call that invokes something that needs the tails file lands on pod number 2 then it wouldn't find it unless they share persisted storage.

**Comment by swcurran** [comment]
That’s my point — with the changes in CL Signatures now in ACA-Py, the local copy of the tails file is not needed by any of the pods after publication.

However, as noted, the change is easy, so all good to go ahead.

**Comment by esune** [comment]
> That’s my point — with the changes in CL Signatures now in ACA-Py, the local copy of the tails file is not needed by any of the pods after publication.

I did not realize/understand the change was already incorporated in ACA-Py (it looks like it is starting with 0.9.0), sorry for the confusion. We could still implement this since it is quick and would be required for previous versions of the agent, but it might not be as critical (we could test what happens first too).

**Comment by esune** [comment]
Increasing priority on this: it is causing significant issues in our production environments when more than one ACA-Py pod is running concurrently.

**Comment by esune** [comment]
Helm updates were pushed to the repo, will close once the `test` instance is upgraded.

@i5okie could we enable HPA in `dev` with a minimum number of pods to start testing this out?
