### ISSUE TITLE
UTF-8 encoding support for credential attributes

### ISSUE THREAD

**Issue by esune** [bcgov/traction#844]
When submitting a credential offer using uncommon characters (such as an emoji, as in the provided example), the Traction tenant responds with a `400` error and hangs the issuance process.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2JrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1b7f15c3dec64df98bc45b8a2ebc51440eb42c21/image.png)

This might be indicative of incorrect handling of character encoding, and should be verified. In particular with Traction, things to check are:
- that the `tenant-proxy` is not modifying the charset encoding for requests being proxied
- that ACA-Py supports UTF-8 as (default?) encoding for plaintext credential attributes
- that Traction plug-ins support UTF-8 as (default?) encoding when handling requests

This issue is to validate and understand the current situation, and determine next steps.

It is a feature required, specifically, by BC Wallet: https://github.com/bcgov/bc-wallet-mobile/issues/1503

**Comment by esune** [comment]
I used the Traction Tenant UI to issue myself a credential and assigned one of the attributes as 😅  - everything went as expected and I was able to correctly store the credential in the BC Wallet.

**Comment by loneil** [comment]
Was just trying this myself too, at least through the Tenant UI > Traction Proxy > My BC Wallet I got other characters transferred through in both the Attribute Name and the Attribute values

![image](https://github.com/bcgov/traction/assets/17445138/c74b3c2c-05e9-4d46-aad7-3657ebd6c9c7)

**Comment by esune** [comment]
Closing as it doesn't seem to be an issue, please feel free to reopen if necessary @jleach
