### ISSUE TITLE
Set custom reservation form in Traction environments

### ISSUE THREAD

**Issue by loneil** [bcgov/traction#868]
As a Traction operator, I want reservation form configuration set up as appropriate in my envs, so that I can collect the details I want from people requesting tenants.
---

Should set the new `reservationForm` values for the Traction environments once deciding what they should be.

DEV
https://github.com/bcgov/traction/blob/main/deploy/traction/values-development.yaml

TEST
https://github.com/bcgov/trust-over-ip-configurations/blob/main/helm-values/traction/values-test.yaml

PROD
https://github.com/bcgov/trust-over-ip-configurations/blob/main/helm-values/traction/values-production.yaml

SANDBOX
https://github.com/bcgov/trust-over-ip-configurations/blob/main/helm-values/traction/values-sandbox.yaml

Could consider adding details to this page too
https://ditp-bc.atlassian.net/wiki/spaces/DESIGN/pages/78348299/Current+Traction+Environment+Configuration

**Comment by loneil** [comment]
@popkinj / @esune Can use this ticket for discussion about Reservation Form config for environments.
Maybe feedback from @swcurran for what we'd want in the Sandbox env?

**Comment by loneil** [comment]
https://github.com/bcgov/trust-over-ip-configurations/pull/166

**Comment by esune** [comment]
Completed as part of the above PR
