### ISSUE TITLE
Error when deleting an API Key

### ISSUE THREAD

**Issue by amanji** [bcgov/traction#888]
When attempting to delete an API Key after creating one in the Tenant, the user is logged out of the Tenant UI and is met with a non-descriptive error.

<img width="1462" alt="Screenshot 2023-10-20 at 1 00 30 PM" src="https://github.com/bcgov/traction/assets/5605464/140d6dc8-86e9-4ba8-9873-58fb9bd5b85f">
<img width="1462" alt="Screenshot 2023-10-20 at 1 00 40 PM" src="https://github.com/bcgov/traction/assets/5605464/40e320f7-47dc-4f57-9fbe-810a10778813">
<img width="1462" alt="Screenshot 2023-10-20 at 1 00 52 PM" src="https://github.com/bcgov/traction/assets/5605464/fdfb128d-be1a-4203-9560-e5f255a43c9b">

**Comment by loneil** [comment]
Argh, sorry @gurjmatharu I was using an API Key testing some things out and just fixed this instantly without thinking if anyone was assigned already since it was just a wrong endpoint.

**Comment by gurjmatharu** [comment]
> Argh, sorry @gurjmatharu I was using an API Key testing some things out and just fixed this instantly without thinking if anyone was assigned already since it was just a wrong endpoint.

no worries!
