### ISSUE TITLE
OCA Endpoint 404

### ISSUE THREAD

**Issue by Jsyro** [bcgov/traction#902]
When navigating to [https://traction-tenant-ui-prod.apps.silver.devops.gov.bc.ca/oca](https://traction-tenant-ui-prod.apps.silver.devops.gov.bc.ca/oca) we see this 404

![image](https://github.com/bcgov/traction/assets/5376854/c2ed0d76-adc6-4ffa-85f3-77339a6bdeb1)

Here is the network request failure.

![thumb-Clipboard - October 31, 2023 9_54 AM](https://github.com/bcgov/traction/assets/5376854/f4f5e29b-39fc-41e7-b436-9e68b1c89dba)

**Comment by esune** [comment]
@Jsyro does the issue ALSO appear in `dev`/`test` or only in `prod`?

**Comment by Jsyro** [comment]
It happens in all three environments

**Comment by jamshale** [comment]
Should be fixed now.
