### ISSUE TITLE
Support deletion of basic message records in messaging plug-in

### ISSUE THREAD

**Issue by esune** [bcgov/traction#903]
The [basicmessage_storage](https://github.com/bcgov/traction/tree/main/plugins/basicmessage_storage) plug-in retains all basic message records so that they can be consumed through the Tenant UI. For privacy and security reasons, it should be possible to delete messages once received, or not retain them at all.

Acceptance Criteria:
* Add endpoint to support programatic deletion of basic messages
* Add setting to disable retention of messages received?

Note: this will have effects on Tenant Ui functionality, that might need to be revisited.

**Comment by esune** [comment]
I can see how "delete all" might be desirable in some scenarios, unsure about the priority.
Another thing to look at is being able to disable storage on a per-tenant basis, to cater to deployments (like Traction) that might need different behaviour depending on their supported use-cases.

**Comment by Jsyro** [comment]
https://github.com/hyperledger/aries-acapy-plugins/pull/52 resolves the most basic of functionality. 

What about future work? 

- [ ]  disable storage option (per tenant? per connection)
- [ ]  delete all message (per tenant? per connection?)
- [x]  Are there unit tests?

**Comment by swcurran** [comment]
Where are the startup issues being tracked? I don’t recall seeing those.

I notice the issues above related to the use of the indy-sdk, which we shouldn’t be using...

**Comment by loneil** [comment]
Same question. We've built and deployed an 0.11 Traction to Dev (and PRs work), and I can build and start local docker on main.

**Comment by Jsyro** [comment]
> Where are the startup issues being tracked? I don’t recall seeing those.

0.11.0 has some issues starting up as a dependency to plugins as the tenant based logging has some file permission issues. @shaangill025 is working on a resolution. 

The basicmessage_storage plugin has a dependency for `mergedeep` that it's pyproject.toml file does not capture properly. I should add that as it's own pull request.


> I notice the issues above related to the use of the indy-sdk, which we shouldn’t be using...

I changed the wallet-type to askar and get the error `aries_askar.error.AskarError: The requested database path was not found` so it appears that askar doesn't want to run in-memory, but I haven't confirmed that either.

**Comment by esune** [comment]
The issue @shaangill025 is working on is related to starting ACA-Py on bare-metal (not Docker).

For Askar runnig in-memory: I am pretty sure I have run it in-memory before, make sure all of the other settings related to the type of storage, etc. have been removed otherwise it might be getting confused.

**Comment by Jsyro** [comment]
Completed, single message deletion enabled, and top level config and sub-wallet configurations to enable/disable. 

This is a breaking change, if deployed acapy instances do not set the plugin config value appropriately, that acapy instance will no longer save messages (incoming or outgoing).
