### ISSUE TITLE
Vue App unit tests fail when updating msw to 2.0.x

### ISSUE THREAD

**Issue by loneil** [bcgov/traction#906]
Noting this while updating other libraries. Did not look into it at all so just leaving `msw` upgrade to later. 
Might be some super simple fix here (or not) if anyone wants to give it a crack just doing that library on it's own.

To reproduce use typical npm package updates then try unit tests

`cd frontend`

`npx npm-check -u`

_select just the msw package and update it to version 2_

`npm ci`

`npm run test`

![image](https://github.com/bcgov/traction/assets/17445138/564414c6-cb3e-4702-9d6f-d74f0415dadb)

**Comment by jamshale** [comment]
Deployed. So should be good.
