### ISSUE TITLE
Allow Innkeeper to restore soft deleted Tenants

### ISSUE THREAD

**Issue by loneil** [bcgov/traction#913]
As a Traction Innkeeper I want to see Tenants that exist in the system but are flagged as deleted, so that I can manage and check on their status
--
Small icon button with hover tooltip that removes the deleted status (and date) when it calls the API. So that we can restore a soft-deleted tenant in the event it's needed

AC

- Next to the DELETED badge in the UI there's a button that restores the tenant (recycle icon with tooltip saying "restore" on hover, or whatever looks good)
- That calls an API endpoint, determine the REST call as part of this ticket and implement. That sets the status back to active and removes the deleted_at timestamp
- Table refreshes on success, toast comes up saying success
- Error toast if it fails

**Comment by popkinj** [comment]
# Notes for restoring a tenanant in traction

## Existing deleted json
```json
{
  "state": "deleted",
  "deleted_at": "2023-12-05T20:02:08.897712Z"
  "created_at": "2023-10-20T19:03:34.225284Z",
  "updated_at": "2023-12-05T20:02:08.897739Z",
  "tenant_id": "eb07f54d-2bb4-46dc-bbfe-0cbf529e88c4",
  "tenant_name": "Jamie",
  "wallet_id": "a0cf5763-4e50-47e4-9d80-a3642de18698",
  "connect_to_endorser": [ ],
  "created_public_did": [ ],
  "auto_issuer": false,
  "enable_ledger_switch": false,
}
```

## Change too
```json
{
  "state": "active",
  "deleted_at": "",
  "created_at": "2023-10-20T19:03:34.225284Z",
  "updated_at": "2023-12-05T20:02:08.897739Z",
  "tenant_id": "eb07f54d-2bb4-46dc-bbfe-0cbf529e88c4",
  "tenant_name": "Jamie",
  "wallet_id": "a0cf5763-4e50-47e4-9d80-a3642de18698",
  "connect_to_endorser": [ ],
  "created_public_did": [ ],
  "auto_issuer": false,
  "enable_ledger_switch": false
}
```

## Get a new authentication token with this command
```bash
curl -X 'POST' \
  'https://traction-tenant-proxy-dev.apps.silver.devops.gov.bc.ca/multitenancy/tenant/<Innkeeper ID here>/token' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "wallet_key": "<private wallet key here>"
}'
```

Then use a PUT request to here: https://traction-tenant-proxy-dev.apps.silver.devops.gov.bc.ca/api/innkeeper/tenants/eb07f54d-2bb4-46dc-bbfe-0cbf529e88c4/config. When using PUT you need to provide all the fields.

## Updating a tenant from deleted (soft) to active.
```bash
curl -X 'PUT' \
  'https://traction-tenant-proxy-dev.apps.silver.devops.gov.bc.ca/innkeeper/tenants/eb07f54d-2bb4-46dc-bbfe-0cbf529e88c4/config' \
  -H 'accept: application/json' \
  -H 'X-API-KEY: <Big long token here>' \
  -H 'Content-Type: application/json' \
  -d '{
  "state": "active",
  "deleted_at": "",
  "created_at": "2023-10-20T19:03:34.225284Z",
  "updated_at": "2023-12-05T20:02:08.897739Z",
  "tenant_id": "eb07f54d-2bb4-46dc-bbfe-0cbf529e88c4",
  "tenant_name": "Jamie",
  "wallet_id": "a0cf5763-4e50-47e4-9d80-a3642de18698",
  "connect_to_endorser": [ ],
  "created_public_did": [ ],
  "auto_issuer": false,
  "enable_ledger_switch": false
}'
```
