### ISSUE TITLE
Review the code in aries-acapy-controllers and adjust as needed to work as intended

### ISSUE THREAD

**Issue by swcurran** [bcgov/traction#925]
See folder: https://github.com/hyperledger/aries-acapy-controllers/TractionIssuanceDemo/

I've found that the Traction Issuance demo is _almost_ working, but not quite, and I'm wondering if someone on the Traction team could help. Sorry to be a pain...I'm not a developer, but am pretty good at following the steps :-) and messing around with things.

What I've noted:

- I followed the steps to get things set up in Traction, setting up the Schema and Cred Def, populating the config.json etc.
- I had to start an ngrok tunnel and used that to expose a public port for the webhooks: ngrok http 8080.
  - That gave me both an HTTP and HTTPS URL
  - I used the HTTPS URL as the Webhooks URL setting in Traction
- Update the config.json file
- Started the app.
- The web page came up on the ngrok URL (and localhost:8080), generated the QR code, scanned it and connected.
- Once connected I can send a message from the BC Wallet and get a response back from Traction, and I can go into Traction and send a message. All working.

**Issue**: With the "autoIssue" set to either true or false, I don't get an offer and the QR code just stays on the screen.

- I can go into the Traction UI and send a message.
- I can go into the Traction UI and send a Credential Offer, and receive a credential.
- I can see the /STATUS endpoint is getting called on port 8080, and I saw other endpoints being used -- some getting 404s (e.g. BasicMessage) and others getting 200s (e.g., Connections).

Can you think of anything that I might be missing?  Does the app need to be updated?

Please add a PR to the repo to fix anything you find, improve the documentation, and ideally -- to add a DockerFile.  I created on one the fly that seemed to work OK:

```
FROM node
COPY . /app
WORKDIR /app
RUN npm install
CMD npm start
```

**Comment by swcurran** [comment]
FYI @esune @loneil

**Comment by loneil** [comment]
I started taking a look at this, can try it next week, the documentation part for webhooks about "For example, if your computer is example.com then the URL will be http://example.com:8080/" definitely isn't helpful IMO and needs more instruction about using ngrok or other as you've noted.

**Comment by swcurran** [comment]
Yes — I was trying to get it working before updating the docs, but couldn’t get it working...

**Comment by loneil** [comment]
@swcurran @esune I added PR with simple instructions that work here
https://github.com/hyperledger/aries-acapy-controllers/pull/96

Can't request reviews on that repo. Can someone add me as as contributor if needed?

**Comment by swcurran** [comment]
Reviewed, approved and merged.  So the flow worked for you, @loneil?  E.g. automatically offered a credential as soon as the connection was established, and automatically displayed the relevant information when the credential issuance completed (as per the video)?  Weird.  I’ll have to try it again.

**Comment by loneil** [comment]
> Reviewed, approved and merged. So the flow worked for you, @loneil? E.g. automatically offered a credential as soon as the connection was established, and automatically displayed the relevant information when the credential issuance completed (as per the video)? Weird. I’ll have to try it again.

Yup, using localtunnel and Sandbox can do the whole flow to BC Wallet or Orbit and get the webhooks coming back and the local app moving on from step to step through connection, issuance, verification

![image](https://github.com/bcgov/traction/assets/17445138/abb2a737-ee9f-4082-8f89-03e309459867)

**Comment by swcurran** [comment]
Dang…I’ll have to try it again. Perhaps we can do a shared screen session to see what I’m doing...

**Comment by esune** [comment]
It sounds like we can close this then?
