### ISSUE TITLE
Suggest moving the Issuer items currently under "Profile" to "Settings"

### ISSUE THREAD

**Issue by swcurran** [bcgov/traction#926]
It seems the more obvious thing to put that item into Settings vs. Profile.  Suggested by @jleach .

**Comment by jleach** [comment]
Wondering if things related to the tenant should be in profile and anything app related in settings. I suppose the endorser stuff could be moved to configuration. I don't quite get why schema storage is in configuration but setting up the endorsers is in settings. So ya, consider moving endorser to configuration. 🤷
