### ISSUE TITLE
Prune old PR images from GHCR

### ISSUE THREAD

**Issue by esune** [bcgov/traction#937]
Automation to purge old container images as well as images generated by closed PRs was introduced as part of the resolution to #598. This has significantly reduced the size of the GHCR, however old PR images that were created before the action was introduced/activated are still in the repository.

Acceptance Criteria:
* Identify which PRs are currently active and should therefore be excluded from the purge process
* Clean-up the GHCR by purging images tagged as `pr-***` that are *NOT* currently in use since the PRs have been already closed.
  * packages that are going to require cleaning-up are `traction-plugins-acapy`, `traction-tenant-proxy` and `traction-tenant-ui `
* This task is a one-off manual clean-up to catch-up to the state that will be managed by the new GHA moving forward.

**Comment by rajpalc7** [comment]
traction-tenant-proxy (Pruned old PR image)

14Version downloads
sha-5c26984
pr-911
Published 23 days ago · Digest …

14Version downloads
sha-edbb27b
pr-912
Published 23 days ago · Digest …

14Version downloads
sha-70ca648
pr-910
Published 23 days ago · Digest …

14Version downloads
sha-0a4cb4d
pr-909
Published 24 days ago · Digest …

15Version downloads
sha-cdf2df9
pr-908
Published 24 days ago · Digest …

18Version downloads
sha-38a0b9d
pr-905
Published about 1 month ago · Digest …

37Version downloads
sha-f22e658
pr-904
Published about 1 month ago · Digest …

37Version downloads
sha-ab1483b
pr-901
Published about 1 month ago · Digest …

39Version downloads
sha-e7525b6
pr-898
Published about 1 month ago · Digest …

39Version downloads
sha-10ddec9
pr-875
Published about 1 month ago · Digest …

39Version downloads
sha-562f96e
pr-895
Published about 1 month ago · Digest …

39Version downloads
sha-fc6a7fe
pr-896
Published about 1 month ago · Digest …

39Version downloads
sha-a1e4cd0
pr-892
Published about 1 month ago · Digest …

39Version downloads
sha-276890c
pr-894
Published about 1 month ago · Digest …

39Version downloads
sha-4210ca4
pr-893
Published about 1 month ago · Digest …

39Version downloads
sha-1a9f7c4
pr-886
Published about 1 month ago · Digest …

39Version downloads
sha-7a5a895
pr-885
Published about 1 month ago · Digest …

593Version downloads
sha-72d9fa0
pr-889
Published about 1 month ago · Digest …

39Version downloads
sha-62925ad
pr-887
Published about 1 month ago · Digest …

39Version downloads
sha-ff0a39e
pr-865
Published about 1 month ago · Digest …

39Version downloads
sha-c7f5c61
pr-871
Published about 2 months ago · Digest …

39Version downloads
sha-f2313a6
pr-884
Published about 2 months ago · Digest …

39Version downloads
sha-cfe42f6
pr-872
Published about 2 months ago · Digest …

39Version downloads
sha-4b3904c
pr-863
Published about 2 months ago · Digest …

39Version downloads
sha-3144a7c
pr-859
Published about 2 months ago · Digest …

39Version downloads
sha-b483ae5
pr-866
Published about 2 months ago · Digest …

39Version downloads
sha-5f31aa7
pr-864
Published about 2 months ago · Digest …

39Version downloads
sha-993e79d
pr-862
Published about 2 months ago · Digest …

39Version downloads
sha-4fff7b0
pr-861
Published about 2 months ago · Digest …

39Version downloads
sha-2cf5a78
pr-854
Published about 2 months ago · Digest …

39Version downloads
sha-106b17e
pr-856
Published about 2 months ago · Digest …

39Version downloads
sha-983e27f
pr-846
Published 2 months ago · Digest …

39Version downloads
sha-63b817a
pr-842
Published 2 months ago · Digest …

39Version downloads
sha-92bf3c7
pr-843
Published 2 months ago · Digest …

39Version downloads
sha-de15dfa
pr-841
Published 2 months ago · Digest …

39Version downloads
sha-acd8c06
pr-839
Published 2 months ago · Digest …


736Version downloads
sha-fd3ca21
pr-838
Published 2 months ago · Digest …

39Version downloads
sha-45f0089
pr-829
Published 2 months ago · Digest …


sha-59b5d28
pr-830
Published 2 months ago · Digest …


108Version downloads
sha-6d16715
pr-828
Published 2 months ago · Digest …

39Version downloads
sha-39178de
pr-827
Published 2 months ago · Digest …

39Version downloads
sha-06394f5
pr-825
Published 2 months ago · Digest …

39Version downloads
sha-4ab1c40
pr-823
Published 2 months ago · Digest …

39Version downloads
sha-d774dd5
pr-822
Published 3 months ago · Digest …

39Version downloads
sha-a3fa725
pr-790
Published 3 months ago · Digest …

39Version downloads
sha-dd6fe16
pr-811
Published 3 months ago · Digest …

39Version downloads
sha-a52b671
pr-817
Published 3 months ago · Digest …

39Version downloads
sha-f3ca8d5
pr-813
Published 3 months ago · Digest …

39Version downloads
sha-04a26a9
pr-816
Published 3 months ago · Digest …

39Version downloads
sha-77fe104
pr-814
Published 3 months ago · Digest …

39Version downloads
sha-1e9a336
pr-793
Published 3 months ago · Digest …

39Version downloads
sha-89e84b3
pr-808
Published 3 months ago · Digest …

39Version downloads
sha-6eed5f2
pr-805
Published 3 months ago · Digest …

39Version downloads
sha-9dc141b
pr-807
Published 3 months ago · Digest …

39Version downloads
sha-8a9f64b
pr-801
Published 3 months ago · Digest …

39Version downloads
sha-84844f4
pr-783
Published 3 months ago · Digest …

39Version downloads
sha-6bbc6ad
pr-799
Published 3 months ago · Digest …

562Version downloads
sha-89f35cf
pr-792
Published 3 months ago · Digest …


186Version downloads
sha-749ea22
pr-788
Published 3 months ago · Digest …

39Version downloads
sha-40db258
pr-784
Published 3 months ago · Digest …

39Version downloads
sha-f08c2eb
pr-782
Published 3 months ago · Digest …

39Version downloads
sha-8af78cc
pr-781
Published 3 months ago · Digest …

39Version downloads
sha-0e27493
pr-780
Published 3 months ago · Digest …

41Version downloads
sha-22b0ad6
pr-778
Published 3 months ago · Digest …

41Version downloads
sha-eb4da65
pr-777
Published 3 months ago · Digest …

43Version downloads
sha-5b68fb3
pr-768
Published 3 months ago · Digest …

45Version downloads
sha-ff996e2
pr-765
Published 3 months ago · Digest …

47Version downloads
sha-a90a14b
pr-759
Published 4 months ago · Digest …

53Version downloads
sha-05f75a3
pr-743
Published 4 months ago · Digest …

53Version downloads
sha-41338cb
pr-736
Published 4 months ago · Digest …

55Version downloads
sha-a66bc4b
pr-755
Published 4 months ago · Digest …

55Version downloads
sha-ea47fc5
pr-752
Published 4 months ago · Digest …

57Version downloads
sha-7dee1a3
pr-751
Published 4 months ago · Digest …

61Version downloads
sha-3513287
pr-745
Published 4 months ago · Digest …

61Version downloads
sha-32f60a4
pr-750
Published 4 months ago · Digest …
63Version downloads
sha-52b42ad
pr-748
Published 4 months ago · Digest …

63Version downloads
sha-4b5c460
pr-737
Published 4 months ago · Digest …

69Version downloads
sha-03112bc
pr-740
Published 4 months ago · Digest …

77Version downloads
sha-fb13e36
pr-738
Published 4 months ago · Digest …


655Version downloads
sha-0a2b423
pr-682
Published 4 months ago · Digest …

81Version downloads
sha-f0af082
pr-731
Published 4 months ago · Digest …

81Version downloads
sha-28fbcc6
pr-729
Published 4 months ago · Digest …

83Version downloads
sha-c3cbaf0
pr-725
Published 4 months ago · Digest …


87Version downloads
sha-96a6c83
pr-727
Published 4 months ago · Digest …


sha-433aa1b
pr-684
Published 5 months ago · Digest …

87Version downloads
sha-62e76b0
pr-718
Published 5 months ago · Digest …

89Version downloads
sha-5636991
pr-703
Published 5 months ago · Digest …

91Version downloads
sha-0160853
pr-715
Published 5 months ago · Digest …

93Version downloads
sha-d738bd7
pr-714
Published 5 months ago · Digest …

95Version downloads
sha-a907a6b
pr-711
Published 5 months ago · Digest …

95Version downloads
sha-52b2d6b
pr-701
Published 5 months ago · Digest …

105Version downloads
sha-fc0cff3
pr-700
Published 5 months ago · Digest …

105Version downloads
sha-09ab00a
pr-676
Published 5 months ago · Digest …


105Version downloads
sha-3289773
pr-692
Published 5 months ago · Digest …

109Version downloads
sha-b9b44d2
pr-694
Published 5 months ago · Digest …

109Version downloads
sha-0882e5c
pr-672
Published 5 months ago · Digest …


117Version downloads
sha-76682f8
pr-680
Published 5 months ago · Digest …

131Version downloads
sha-b8dc532
pr-677
Published 5 months ago · Digest …


127Version downloads
sha-7102ed5
pr-673
Published 6 months ago · Digest …

145Version downloads
sha-ac40637
pr-664
Published 6 months ago · Digest …

175Version downloads
sha-82c7e14
pr-671
Published 6 months ago · Digest …

154Version downloads
sha-9b1ad72
pr-668
Published 6 months ago · Digest …

160Version downloads
sha-17ca417
pr-665
Published 6 months ago · Digest …

158Version downloads
sha-512bf57
pr-660
Published 6 months ago · Digest …

154Version downloads
sha-a26b3fa
pr-649
Published 6 months ago · Digest …

156Version downloads
sha-8f23c62
pr-639
Published 6 months ago · Digest …

155Version downloads
sha-1569449
pr-642
Published 6 months ago · Digest …

154Version downloads
sha-5d17455
pr-638
Published 6 months ago · Digest …

158Version downloads
sha-b6e8c71
pr-623
Published 6 months ago · Digest …

158Version downloads
sha-4d8a0dc
pr-631
Published 6 months ago · Digest …

160Version downloads
sha-6192399
pr-630
Published 6 months ago · Digest …

156Version downloads
sha-04e050d
pr-629
Published 6 months ago · Digest …


157Version downloads
sha-2ac58da
pr-604
Published 6 months ago · Digest …

154Version downloads
sha-b143081
pr-625
Published 6 months ago · Digest …


25,968Version downloads
sha-1dfb2ef
pr-615
Published 6 months ago · Digest …

154Version downloads
sha-211d7ab
pr-622
Published 6 months ago · Digest …

154Version downloads
sha-91fe38f
pr-614
Published 6 months ago · Digest …


178Version downloads
sha-1233607
pr-599
Published 6 months ago · Digest …

155Version downloads
sha-0724b14
pr-605
Published 6 months ago · Digest …


155Version downloads
sha-b3f659b
pr-606
Published 6 months ago · Digest …



149Version downloads
sha-c750ef0
pr-602
Published 6 months ago · Digest …


155Version downloads
sha-43c693f
pr-601
Published 6 months ago · Digest …


186Version downloads
sha-4548ed9
pr-586
Published 6 months ago · Digest …


158Version downloads
sha-2daa1c1
pr-580
Published 7 months ago · Digest …

**Comment by rajpalc7** [comment]
traction-tenant-acapy  (Pruned old PR image)

14Version downloads
sha-5c26984
pr-911
Published 23 days ago · Digest …

14Version downloads
sha-edbb27b
pr-912
Published 23 days ago · Digest …

14Version downloads
sha-70ca648
pr-910
Published 23 days ago · Digest …

14Version downloads
sha-0a4cb4d
pr-909
Published 24 days ago · Digest …

15Version downloads
sha-cdf2df9
pr-908
Published 24 days ago · Digest …

18Version downloads
sha-38a0b9d
pr-905
Published about 1 month ago · Digest …

37Version downloads
sha-f22e658
pr-904
Published about 1 month ago · Digest …

37Version downloads
sha-ab1483b
pr-901
Published about 1 month ago · Digest …

39Version downloads
sha-e7525b6
pr-898
Published about 1 month ago · Digest …

39Version downloads
sha-10ddec9
pr-875
Published about 1 month ago · Digest …

39Version downloads
sha-562f96e
pr-895
Published about 1 month ago · Digest …

39Version downloads
sha-fc6a7fe
pr-896
Published about 1 month ago · Digest …

39Version downloads
sha-a1e4cd0
pr-892
Published about 1 month ago · Digest …

39Version downloads
sha-276890c
pr-894
Published about 1 month ago · Digest …

39Version downloads
sha-4210ca4
pr-893
Published about 1 month ago · Digest …

39Version downloads
sha-1a9f7c4
pr-886
Published about 1 month ago · Digest …

39Version downloads
sha-7a5a895
pr-885
Published about 1 month ago · Digest …

593Version downloads
sha-72d9fa0
pr-889
Published about 1 month ago · Digest …

39Version downloads
sha-62925ad
pr-887
Published about 1 month ago · Digest …

39Version downloads
sha-ff0a39e
pr-865
Published about 1 month ago · Digest …

39Version downloads
sha-c7f5c61
pr-871
Published about 2 months ago · Digest …

39Version downloads
sha-f2313a6
pr-884
Published about 2 months ago · Digest …

39Version downloads
sha-cfe42f6
pr-872
Published about 2 months ago · Digest …

39Version downloads
sha-4b3904c
pr-863
Published about 2 months ago · Digest …

39Version downloads
sha-3144a7c
pr-859
Published about 2 months ago · Digest …

39Version downloads
sha-b483ae5
pr-866
Published about 2 months ago · Digest …

39Version downloads
sha-5f31aa7
pr-864
Published about 2 months ago · Digest …

39Version downloads
sha-993e79d
pr-862
Published about 2 months ago · Digest …

39Version downloads
sha-4fff7b0
pr-861
Published about 2 months ago · Digest …

39Version downloads
sha-2cf5a78
pr-854
Published about 2 months ago · Digest …

39Version downloads
sha-106b17e
pr-856
Published about 2 months ago · Digest …

39Version downloads
sha-983e27f
pr-846
Published 2 months ago · Digest …

39Version downloads
sha-63b817a
pr-842
Published 2 months ago · Digest …

39Version downloads
sha-92bf3c7
pr-843
Published 2 months ago · Digest …

39Version downloads
sha-de15dfa
pr-841
Published 2 months ago · Digest …

39Version downloads
sha-acd8c06
pr-839
Published 2 months ago · Digest …

736Version downloads
sha-fd3ca21
pr-838
Published 2 months ago · Digest …

39Version downloads
sha-45f0089
pr-829
Published 2 months ago · Digest …

sha-59b5d28
pr-830
Published 2 months ago · Digest …

108Version downloads
sha-6d16715
pr-828
Published 2 months ago · Digest …

39Version downloads
sha-39178de
pr-827
Published 2 months ago · Digest …

39Version downloads
sha-06394f5
pr-825
Published 2 months ago · Digest …

39Version downloads
sha-4ab1c40
pr-823
Published 2 months ago · Digest …

39Version downloads
sha-d774dd5
pr-822
Published 3 months ago · Digest …

39Version downloads
sha-a3fa725
pr-790
Published 3 months ago · Digest …

39Version downloads
sha-dd6fe16
pr-811
Published 3 months ago · Digest …

39Version downloads
sha-a52b671
pr-817
Published 3 months ago · Digest …

39Version downloads
sha-f3ca8d5
pr-813
Published 3 months ago · Digest …

39Version downloads
sha-04a26a9
pr-816
Published 3 months ago · Digest …

39Version downloads
sha-77fe104
pr-814
Published 3 months ago · Digest …

39Version downloads
sha-1e9a336
pr-793
Published 3 months ago · Digest …

39Version downloads
sha-89e84b3
pr-808
Published 3 months ago · Digest …

39Version downloads
sha-6eed5f2
pr-805
Published 3 months ago · Digest …

39Version downloads
sha-9dc141b
pr-807
Published 3 months ago · Digest …

39Version downloads
sha-8a9f64b
pr-801
Published 3 months ago · Digest …

39Version downloads
sha-84844f4
pr-783
Published 3 months ago · Digest …

39Version downloads
sha-6bbc6ad
pr-799
Published 3 months ago · Digest …

562Version downloads
sha-89f35cf
pr-792
Published 3 months ago · Digest …

186Version downloads
sha-749ea22
pr-788
Published 3 months ago · Digest …

39Version downloads
sha-40db258
pr-784
Published 3 months ago · Digest …

39Version downloads
sha-f08c2eb
pr-782
Published 3 months ago · Digest …

39Version downloads
sha-8af78cc
pr-781
Published 3 months ago · Digest …

39Version downloads
sha-0e27493
pr-780
Published 3 months ago · Digest …

41Version downloads
sha-22b0ad6
pr-778
Published 3 months ago · Digest …

41Version downloads
sha-eb4da65
pr-777
Published 3 months ago · Digest …

43Version downloads
sha-5b68fb3
pr-768
Published 3 months ago · Digest …

45Version downloads
sha-ff996e2
pr-765
Published 3 months ago · Digest …

47Version downloads
sha-a90a14b
pr-759
Published 4 months ago · Digest …

53Version downloads
sha-05f75a3
pr-743
Published 4 months ago · Digest …

53Version downloads
sha-41338cb
pr-736
Published 4 months ago · Digest …

55Version downloads
sha-a66bc4b
pr-755
Published 4 months ago · Digest …

55Version downloads
sha-ea47fc5
pr-752
Published 4 months ago · Digest …

57Version downloads
sha-7dee1a3
pr-751
Published 4 months ago · Digest …

61Version downloads
sha-3513287
pr-745
Published 4 months ago · Digest …

61Version downloads
sha-32f60a4
pr-750
Published 4 months ago · Digest …
63Version downloads
sha-52b42ad
pr-748
Published 4 months ago · Digest …

63Version downloads
sha-4b5c460
pr-737
Published 4 months ago · Digest …

69Version downloads
sha-03112bc
pr-740
Published 4 months ago · Digest …

77Version downloads
sha-fb13e36
pr-738
Published 4 months ago · Digest …

655Version downloads
sha-0a2b423
pr-682
Published 4 months ago · Digest …

81Version downloads
sha-f0af082
pr-731
Published 4 months ago · Digest …

81Version downloads
sha-28fbcc6
pr-729
Published 4 months ago · Digest …

83Version downloads
sha-c3cbaf0
pr-725
Published 4 months ago · Digest …

87Version downloads
sha-96a6c83
pr-727
Published 4 months ago · Digest …

sha-433aa1b
pr-684
Published 5 months ago · Digest …

87Version downloads
sha-62e76b0
pr-718
Published 5 months ago · Digest …

89Version downloads
sha-5636991
pr-703
Published 5 months ago · Digest …

91Version downloads
sha-0160853
pr-715
Published 5 months ago · Digest …

93Version downloads
sha-d738bd7
pr-714
Published 5 months ago · Digest …

95Version downloads
sha-a907a6b
pr-711
Published 5 months ago · Digest …

95Version downloads
sha-52b2d6b
pr-701
Published 5 months ago · Digest …

105Version downloads
sha-fc0cff3
pr-700
Published 5 months ago · Digest …

105Version downloads
sha-09ab00a
pr-676
Published 5 months ago · Digest …

105Version downloads
sha-3289773
pr-692
Published 5 months ago · Digest …

109Version downloads
sha-b9b44d2
pr-694
Published 5 months ago · Digest …

109Version downloads
sha-0882e5c
pr-672
Published 5 months ago · Digest …

117Version downloads
sha-76682f8
pr-680
Published 5 months ago · Digest …

131Version downloads
sha-b8dc532
pr-677
Published 5 months ago · Digest …

127Version downloads
sha-7102ed5
pr-673
Published 6 months ago · Digest …

145Version downloads
sha-ac40637
pr-664
Published 6 months ago · Digest …

175Version downloads
sha-82c7e14
pr-671
Published 6 months ago · Digest …

154Version downloads
sha-9b1ad72
pr-668
Published 6 months ago · Digest …

160Version downloads
sha-17ca417
pr-665
Published 6 months ago · Digest …

158Version downloads
sha-512bf57
pr-660
Published 6 months ago · Digest …

154Version downloads
sha-a26b3fa
pr-649
Published 6 months ago · Digest …

156Version downloads
sha-8f23c62
pr-639
Published 6 months ago · Digest …

155Version downloads
sha-1569449
pr-642
Published 6 months ago · Digest …

154Version downloads
sha-5d17455
pr-638
Published 6 months ago · Digest …

158Version downloads
sha-b6e8c71
pr-623
Published 6 months ago · Digest …

158Version downloads
sha-4d8a0dc
pr-631
Published 6 months ago · Digest …

160Version downloads
sha-6192399
pr-630
Published 6 months ago · Digest …

156Version downloads
sha-04e050d
pr-629
Published 6 months ago · Digest …

157Version downloads
sha-2ac58da
pr-604
Published 6 months ago · Digest …

154Version downloads
sha-b143081
pr-625
Published 6 months ago · Digest …

25,968Version downloads
sha-1dfb2ef
pr-615
Published 6 months ago · Digest …

154Version downloads
sha-211d7ab
pr-622
Published 6 months ago · Digest …

154Version downloads
sha-91fe38f
pr-614
Published 6 months ago · Digest …

178Version downloads
sha-1233607
pr-599
Published 6 months ago · Digest …

155Version downloads
sha-0724b14
pr-605
Published 6 months ago · Digest …

155Version downloads
sha-b3f659b
pr-606
Published 6 months ago · Digest …

149Version downloads
sha-c750ef0
pr-602
Published 6 months ago · Digest …

155Version downloads
sha-43c693f
pr-601
Published 6 months ago · Digest …

186Version downloads
sha-4548ed9
pr-586
Published 6 months ago · Digest …

158Version downloads
sha-2daa1c1
pr-580
Published 7 months ago · Digest …

27Version downloads
sha-3cabc63
Published 23 days ago · Digest …

20Version downloads
sha-a39cac4
Published 23 days ago · Digest …

20Version downloads
sha-edbb27b
pr-912
Published 23 days ago · Digest …

38Version downloads
sha-43db4da
Published 23 days ago · Digest …

23Version downloads
sha-70ca648
pr-910
Published 23 days ago · Digest …

29Version downloads
sha-5261347
Published 23 days ago · Digest …

28Version downloads
sha-0a4cb4d
pr-909
Published 23 days ago · Digest …

38Version downloads
sha-013c498
Published 24 days ago · Digest …

34Version downloads
sha-cdf2df9
pr-908
Published 24 days ago · Digest …

39Version downloads
sha-516800f
Published 29 days ago · Digest …

69Version downloads
sha-38a0b9d
pr-905
Published about 1 month ago · Digest …

44Version downloads
sha-f22e658
pr-904
Published about 1 month ago · Digest …

49Version downloads
sha-ab1483b
pr-901
Published about 1 month ago · Digest …

47Version downloads
sha-e7525b6
pr-898
Published about 1 month ago · Digest …

51Version downloads
sha-10ddec9
pr-875
Published about 1 month ago · Digest …

218Version downloads
sha-562f96e
pr-895
Published about 1 month ago · Digest …

46Version downloads
sha-fc6a7fe
pr-896
Published about 1 month ago · Digest …

53Version downloads
sha-a1e4cd0
pr-892
Published about 1 month ago · Digest …

46Version downloads
sha-276890c
pr-894
Published about 1 month ago · Digest …

51Version downloads
sha-4210ca4
pr-893
Published about 1 month ago · Digest …

48Version downloads
sha-1a9f7c4
pr-886
Published about 1 month ago · Digest …

46Version downloads
sha-7a5a895
pr-885
Published about 1 month ago · Digest …


434Version downloads
sha-72d9fa0
pr-889
Published about 1 month ago · Digest …

52Version downloads
sha-62925ad
pr-887
Published about 1 month ago · Digest …

73Version downloads
sha-ff0a39e
pr-865
Published about 1 month ago · Digest …

52Version downloads
sha-c7f5c61
pr-871
Published about 2 months ago · Digest …

52Version downloads
sha-f2313a6
pr-884
Published about 2 months ago · Digest …

46Version downloads
sha-cfe42f6
pr-872
Published about 2 months ago · Digest …

52Version downloads
sha-4b3904c
pr-863
Published about 2 months ago · Digest …

73Version downloads
sha-3144a7c
pr-859
Published about 2 months ago · Digest …

48Version downloads
sha-b483ae5
pr-866
Published about 2 months ago · Digest …

46Version downloads
sha-5f31aa7
pr-864
Published about 2 months ago · Digest …

46Version downloads
sha-993e79d
pr-862
Published about 2 months ago · Digest …

46Version downloads
sha-4fff7b0
pr-861
Published about 2 months ago · Digest …

49Version downloads
sha-2cf5a78
pr-854
Published about 2 months ago · Digest …

41Version downloads
sha-106b17e
pr-856
Published about 2 months ago · Digest …

50Version downloads
sha-983e27f
pr-846
Published 2 months ago · Digest …

52Version downloads
sha-63b817a
pr-842
Published 2 months ago · Digest …

41Version downloads
sha-92bf3c7
pr-843
Published 2 months ago · Digest …

53Version downloads
sha-de15dfa
pr-841
Published 2 months ago · Digest …

68Version downloads
sha-acd8c06
pr-839
Published 2 months ago · Digest …


772Version downloads
sha-fd3ca21
pr-838


sha-59b5d28
pr-830
Published 2 months ago · Digest …


47Version downloads
sha-6d16715
pr-828
Published 2 months ago · Digest …

47Version downloads
sha-39178de
pr-827
Published 2 months ago · Digest …

48Version downloads
sha-06394f5
pr-825
Published 2 months ago · Digest …

47Version downloads
sha-4ab1c40
pr-823
Published 2 months ago · Digest …

47Version downloads
sha-d774dd5
pr-822
Published 2 months ago · Digest …

47Version downloads
sha-a3fa725
pr-790
Published 2 months ago · Digest …

45Version downloads
sha-dd6fe16
pr-811
Published 2 months ago · Digest …

44Version downloads
sha-a52b671
pr-817
Published 2 months ago · Digest …

44Version downloads
sha-f3ca8d5
pr-813
Published 3 months ago · Digest …

45Version downloads
sha-04a26a9
pr-816
Published 3 months ago · Digest …

52Version downloads
sha-77fe104
pr-814
Published 3 months ago · Digest …

45Version downloads
sha-1e9a336
pr-793
Published 3 months ago · Digest …

72Version downloads
sha-89e84b3
pr-808
Published 3 months ago · Digest …

123Version downloads
sha-6eed5f2
pr-805
Published 3 months ago · Digest …

44Version downloads
sha-9dc141b
pr-807
Published 3 months ago · Digest …

50Version downloads
sha-8a9f64b
pr-801
Published 3 months ago · Digest …

68Version downloads
sha-84844f4
pr-783
Published 3 months ago · Digest …

44Version downloads
sha-6bbc6ad
pr-799
Published 3 months ago · Digest …


808Version downloads
sha-89f35cf
pr-792
Published 3 months ago · Digest …


82Version downloads
sha-749ea22
pr-788
Published 3 months ago · Digest …

51Version downloads
sha-40db258
pr-784
Published 3 months ago · Digest …

45Version downloads
sha-f08c2eb
pr-782
Published 3 months ago · Digest …


49Version downloads
sha-8af78cc
pr-781
Published 3 months ago · Digest …


49Version downloads
sha-0e27493
pr-780
Published 3 months ago · Digest …


52Version downloads
sha-22b0ad6
pr-778
Published 3 months ago · Digest …

51Version downloads
sha-eb4da65
pr-777
Published 3 months ago · Digest …

48Version downloads
sha-5b68fb3
pr-768
Published 3 months ago · Digest …

52Version downloads
sha-ff996e2
pr-765
Published 3 months ago · Digest …

56Version downloads
sha-a90a14b
pr-759
Published 4 months ago · Digest …

73Version downloads
sha-05f75a3
pr-743
Published 4 months ago · Digest …

58Version downloads
sha-41338cb
pr-736
Published 4 months ago · Digest …

76Version downloads
sha-a66bc4b
pr-755
Published 4 months ago · Digest …

63Version downloads
sha-ea47fc5
pr-752
Published 4 months ago · Digest …

62Version downloads
sha-7dee1a3
pr-751
Published 4 months ago · Digest …


70Version downloads
sha-3513287
pr-745
Published 4 months ago · Digest …


66Version downloads
sha-32f60a4
pr-750
Published 4 months ago · Digest …

76Version downloads
sha-52b42ad
pr-748
Published 4 months ago · Digest …

76Version downloads
sha-4b5c460
pr-737
Published 4 months ago · Digest …

107Version downloads
sha-03112bc
pr-740
Published 4 months ago · Digest …

97Version downloads
sha-fb13e36
pr-738
Published 4 months ago · Digest …


785Version downloads
sha-0a2b423
pr-682
Published 4 months ago · Digest …

93Version downloads
sha-f0af082
pr-731
Published 4 months ago · Digest …

86Version downloads
sha-28fbcc6
pr-729
Published 4 months ago · Digest …

88Version downloads
sha-c3cbaf0
pr-725
Published 4 months ago · Digest …


92Version downloads
sha-96a6c83
pr-727
Published 4 months ago · Digest …



sha-433aa1b
pr-684
Published 4 months ago · Digest …


96Version downloads
sha-9f088e2
pr-718
Published 5 months ago · Digest …

103Version downloads
sha-5636991
pr-703
Published 5 months ago · Digest …


98Version downloads
sha-0160853
pr-715
Published 5 months ago · Digest …

102Version downloads
sha-d738bd7
pr-714
Published 5 months ago · Digest …

104Version downloads
sha-a907a6b
pr-711
Published 5 months ago · Digest …

108Version downloads
sha-52b2d6b
pr-701
Published 5 months ago · Digest …


117Version downloads
sha-fc0cff3
pr-700
Published 5 months ago · Digest …


120Version downloads
sha-09ab00a
pr-676
Published 5 months ago · Digest …


110Version downloads
sha-3289773
pr-692
Published 5 months ago · Digest …


107Version downloads
sha-b9b44d2
pr-694
Published 5 months ago · Digest …


115Version downloads
sha-0882e5c
pr-672
Published 5 months ago · Digest …


129Version downloads
sha-76682f8
pr-680
Published 5 months ago · Digest …


128Version downloads
sha-b8dc532
pr-677
Published 5 months ago · Digest …


128Version downloads
sha-7102ed5
pr-673
Published 5 months ago · Digest …


147Version downloads
sha-ac40637
pr-664
Published 6 months ago · Digest …


168Version downloads
sha-82c7e14
pr-671
Published 6 months ago · Digest …


151Version downloads
sha-9b1ad72
pr-668
Published 6 months ago · Digest …


157Version downloads
sha-d415e86
pr-669
Published 6 months ago · Digest …


153Version downloads
sha-17ca417
pr-665
Published 6 months ago · Digest …

155Version downloads
sha-512bf57
pr-660
Published 6 months ago · Digest …

151Version downloads
sha-a26b3fa
pr-649
Published 6 months ago · Digest …

152Version downloads
sha-8f23c62
pr-639
Published 6 months ago · Digest …

157Version downloads
sha-1569449
pr-642
Published 6 months ago · Digest …


151Version downloads
sha-5d17455
pr-638
Published 6 months ago · Digest …


161Version downloads
sha-b6e8c71
pr-623
Published 6 months ago · Digest …


160Version downloads
sha-4d8a0dc
pr-631
Published 6 months ago · Digest …

165Version downloads
sha-6192399
pr-630
Published 6 months ago · Digest …

153Version downloads
sha-04e050d
pr-629
Published 6 months ago · Digest …


159Version downloads
sha-2ac58da
pr-604
Published 6 months ago · Digest …

151Version downloads
sha-b143081
pr-625
Published 6 months ago · Digest …


1,882Version downloads
sha-1dfb2ef
pr-615
Published 6 months ago · Digest …

151Version downloads
sha-211d7ab
pr-622
Published 6 months ago · Digest …

151Version downloads
sha-91fe38f
pr-614
Published 6 months ago · Digest …

188Version downloads
sha-1233607
pr-599
Published 6 months ago · Digest …

157Version downloads
sha-0724b14
pr-605
Published 6 months ago · Digest …

157Version downloads
sha-b3f659b
pr-606
Published 6 months ago · Digest …


151Version downloads
sha-c750ef0
pr-602
Published 6 months ago · Digest …

152Version downloads
sha-43c693f
pr-601
Published 6 months ago · Digest …


187Version downloads
sha-4548ed9
pr-586
Published 6 months ago · Digest …

155Version downloads
sha-2daa1c1
pr-580
Published 7 months ago · Digest …

**Comment by esune** [comment]
Thanks @rajpalc7. Would you mind posting the steps/info you used to delete the packages for future reference?
Once that is in we can close this issue as the registry is now pretty clean.

**Comment by rajpalc7** [comment]
I looked at all the PR's that were in close state on https://github.com/bcgov/traction/pulls?q=is%3Apr+is%3Aclosed and based on that information i had to manually purge images that were tagged as pr-***

**Comment by esune** [comment]
> I looked at all the PR's that were in close state on https://github.com/bcgov/traction/pulls?q=is%3Apr+is%3Aclosed and based on that information i had to manually purge images that were tagged as pr-***

Are there any resources/commands you could link to for future reference (if we happen to need to do this again here or in another repo)?

**Comment by rajpalc7** [comment]
```docker login ghcr.io -u <username> -p <PAT>
docker rmi ghcr.io/<username>/<repository>:image tag```

For example " docker login ghcr.io -u rachauha -p <PAT>
