### ISSUE TITLE
Solve issues with some tenant UI skipped tests

### ISSUE THREAD

**Issue by loneil** [bcgov/traction#941]
Some pending issues with Vue app unit tests that popped up after library upgrades. I couldn't find any solution top the below ones (in a limited timeframe) so tracking them here.

Nothing going wrong with the code in question for these as far as I can see, just test framework(?) problems.

Possibly subsequent library updates could fix things? Can check they don't pass before looking at a fix.

**Various store tests**
governanceStore.test.ts
issuerStore.test.ts
tenantStore.test.ts
verifierStore.test.ts
![image](https://github.com/bcgov/traction/assets/17445138/46af708b-fefc-4a4f-b4a0-779b76fcfcef)

**AcceptInviteForm.test.ts**

![image](https://github.com/bcgov/traction/assets/17445138/8020c5bd-95ec-48fb-9d51-36b71db1aa7e)

**Comment by jamshale** [comment]
These probably aren't very important tests. I think they are testing that the toast notification is triggered. Seems like vue changes the components quite a bit that effects these types of tests. Should find a way to make them less brittle or we could decide just not to test things like this. 

However, I think this test in particular might be that something else is now triggering a toast when it wasn't expected before.

**Comment by loneil** [comment]
Relevant ones of these ended up resolved with some library updates at one point
