### ISSUE TITLE
Failures for GHCR prune task

### ISSUE THREAD

**Issue by esune** [bcgov/traction#950]
The GHA responsible for pruning old container images failed its execution. The error seems to be related to a malformed/missing token - see https://github.com/bcgov/traction/actions/runs/7095370789/job/19420872161

**Comment by rajpalc7** [comment]
https://github.com/bcgov/traction/actions/runs/7133186796/job/19425331189  - Successful test run.

**Comment by esune** [comment]
> https://github.com/bcgov/traction/actions/runs/7133186796/job/19425331189 - Successful workflow run.
> 
> Hi @esune, so https://github.com/snok/container-retention-policy/tree/main made some changes this morning and they want us to use token-type as github-token or PAT so i have made the new changes accordingly and our workflow is running successfully again.

Can we use a service token for the repository, rather than a PAT associated to your user?

**Comment by rajpalc7** [comment]
https://github.com/bcgov/traction/actions/runs/7135573072/job/19432583988  - looks like service token work only if there is one image, it doesnt support multiple images .

https://github.com/bcgov/traction/actions/runs/7135595743 - Successful run with one image

**Comment by rajpalc7** [comment]
<img width="1244" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0JDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0cf0ff256f493bf83af430fd451a7590b1205b72/image.png" alt="image.png" />

**Comment by esune** [comment]
Resolved by #951
