### ISSUE TITLE
Remove requirement for email address for full self-serve instances of Traction

### ISSUE THREAD

**Issue by esune** [bcgov/traction#952]
This is specific for our sandbox instance, to restrict the amount of potential PII being collected (although not used).

Since the email address is not being used when a tenant is self-provisioned, we'd like to be able to NOT have to request an email address.

**Comment by loneil** [comment]
There's a mandatory field for "organization" as well, should that remain mandatory?



![Image](https://github.com/bcgov/traction/assets/17445138/c93434ef-1643-4e53-9524-ebbcb1311979)

**Comment by esune** [comment]
No, I think we can remove it as well.

**Comment by loneil** [comment]
The backend has the contact email as mandatory, so went with Stephen's idea of just posting a dummy email address to keep the changes scoped to frontend. (could pull into plugin as well if we don't think this is acceptable)

Traction PR: https://github.com/bcgov/traction/pull/1023

Sandbox config PR: https://github.com/bcgov/trust-over-ip-configurations/pull/184
