### ISSUE TITLE
[FEATURE] add option for a ttl when request a tenant token

### ISSUE THREAD

**Issue by PatStLouis** [bcgov/traction#972]
I would like to see an optional `ttl` field in the request body for the `/multitenancy/tenant/{tenant_id}/token` endpoint.

Some applications might require a token with an expiration date of a desired length set.

@esune thoughts on this?

**Comment by esune** [comment]
Circling back on this, I had not though about it before, but think it would be a valuable option. Thoughts @loneil?

We also might want to move the conversation to the https://github.com/hyperledger/aries-acapy-plugins repo as we're planning on moving the `multitenant_provider` plugin for Traction there and remove the (now) duplicate code in this repo.

**Comment by esune** [comment]
Replaced by https://github.com/hyperledger/aries-acapy-plugins/issues/104
