### ISSUE TITLE
ngrok now requires a free account and authtoken

### ISSUE THREAD

**Issue by russorat** [bcgov/traction#978]
PM from ngrok here. I'm opening this issue to let you know what ngrok has recently started requiring a free account and authtoken to start the agent. It looks like your software might already work with an authtoken, but there might be users or integrations or docs that need to updated.

Please reach out to support@ngrok.com if you are having any issues. 

Thanks again for using ngrok!

I've copied the original notice posted to twitter below:
```
As a part of our ongoing efforts to make ngrok more secure, starting on December 19, 2023, all usage of ngrok will require an account on either our free or paid tiers. 

To connect to the ngrok service via the agent, SDK, or ingress controller, you must add a valid authtoken that is linked to an active free or paid account. Any new or existing connections without a valid authtoken will result in error code 4018.

Learn more here: https://ngrok.com/docs/errors/err_ngrok_4018/
```

**Comment by loneil** [comment]
The Traction docker compose already has ngrok auth token setup in it that we use for local dev (and only needs the 1 tunnel for the `ngrok-traction-agent` container). So I think this is not a concern for this repo in particular.
