### ISSUE TITLE
When rejecting a credential offer, Tenant UI should send a problem report before deleting the exchange record locally

### ISSUE THREAD

**Issue by Jsyro** [bcgov/traction#999]
If the user opts to decline/reject the credential offer. It does send a problem report through the connection. 

It should, however the existing code just deletes the local record and does not use the POST to the issue-credential/<cred_exch_id>/problem-report endpoint. 

There may be a standard payload in the documentation, but i'm not sure. 

https://github.com/hyperledger/aries-rfcs/blob/main/features/0036-issue-credential/README.md

**Comment by esune** [comment]
Problem report RFC: https://github.com/hyperledger/aries-rfcs/tree/main/features/0035-report-problem

It looks like we should be hitting the appropriate problem report endpoint for the credential exchange (`/issue-credential/records/{cred_ex_id}/problem-report` and `/issue-credential-2.0/records/{cred_ex_id}/problem-report`) with details about what happened.

**Comment by loneil** [comment]
Easy enough to do the ACA-Py API call to post a problem report when the user rejects the credential offer through the Tenant UI.

But is that the flow? Whatever controller interacting with it's agent (in this case the Tenant UI on behalf of the Tenant) manually makes the admin API call for that? I'd had it in my mind that the problem-report would be more automatic than that. Like in VC-Auth is the declined presentation request a controller-driven problem report send? 
Maybe it is and I have it wrong but would just want to make sure it's consistent (IE, make sure it's not something that's missing in ACA-Py, or a auto setting or something)

**Comment by esune** [comment]
> 
> But is that the flow? Whatever controller interacting with it's agent (in this case the Tenant UI on behalf of the Tenant) manually makes the admin API call for that?

Yes, that is the way the protocol was specified. In the case of BC Wallet, it is the (human) controller that triggers the problem report by refusing to send a response to the proof.

**Comment by loneil** [comment]
Cool, then this is probably ready to go to add to Tenant UI if it's needed.

**Comment by loneil** [comment]
https://github.com/bcgov/traction/pull/1029
